# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html
parameters:
  app.frontend_url: '%env(FRONTEND_URL)%'
  app.sender_email: '%env(MAILER_SENDER_EMAIL)%'
  app.sender_name: '%env(MAILER_SENDER_NAME)%'
  app.ws_publish_url: 'http://127.0.0.1:8082'
  app.forge_api_url: '%env(default:FORGE_API_URL:https://forge.butterfly-effect.dev)%'
  app.forge_api_key: '%env(default::FORGE_API_KEY)%'
  app.google_maps_api_key: '%env(default::GOOGLE_MAPS_API_KEY)%'
services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $appUrl: '%app.frontend_url%'
      string $senderEmail: '%app.sender_email%'
      string $senderName: '%app.sender_name%'
      string $wsPublishUrl: '%env(default:app.ws_publish_url:WS_PUBLISH_URL)%'
      string $wsPublishSecret: '%env(WS_PUBLISH_SECRET)%'
      string $forgeApiUrl: '%app.forge_api_url%'
      string $forgeApiKey: '%app.forge_api_key%'
      string $googleMapsApiKey: '%app.google_maps_api_key%'
  'App\\':
    resource: '../src/'
