<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630102325 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media_object (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) NOT NULL, original_name VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, size INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uploaded_by_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14D43132A2B28FE8 ON media_object (uploaded_by_id)');
        $this->addSql('ALTER TABLE media_object ADD CONSTRAINT FK_14D43132A2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD is_read BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD type VARCHAR(255) DEFAULT NULL');
        $this->addSql('UPDATE "user" SET type = \'patient\' WHERE type IS NULL');
        $this->addSql('ALTER TABLE "user" ALTER type SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD groupe_sanguin VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD allergies TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD contacts_urgence TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD specialite VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD numero_ordre VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD est_valide BOOLEAN DEFAULT false');
        $this->addSql('ALTER TABLE "user" ADD disponibilites TEXT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media_object DROP CONSTRAINT FK_14D43132A2B28FE8');
        $this->addSql('DROP TABLE media_object');
        $this->addSql('ALTER TABLE message DROP is_read');
        $this->addSql('ALTER TABLE "user" DROP type');
        $this->addSql('ALTER TABLE "user" DROP groupe_sanguin');
        $this->addSql('ALTER TABLE "user" DROP allergies');
        $this->addSql('ALTER TABLE "user" DROP contacts_urgence');
        $this->addSql('ALTER TABLE "user" DROP specialite');
        $this->addSql('ALTER TABLE "user" DROP numero_ordre');
        $this->addSql('ALTER TABLE "user" DROP est_valide');
        $this->addSql('ALTER TABLE "user" DROP disponibilites');
    }
}
