<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260801150000 extends AbstractMigration {
    public function getDescription(): string { return 'Ajoute les protocoles de premiers gestes versionnés.'; }
    public function up(Schema $schema): void {
        $this->addSql("CREATE TABLE protocole_premiers_gestes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(120) NOT NULL, titre VARCHAR(180) NOT NULL, statut VARCHAR(20) NOT NULL, niveau_urgence VARCHAR(20) NOT NULL, population VARCHAR(20) NOT NULL, version VARCHAR(40) NOT NULL, source_clinique TEXT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_protocole_slug_version ON protocole_premiers_gestes (slug, version)');
        $this->addSql('CREATE TABLE protocole_etape (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, protocole_id INT NOT NULL, position INT NOT NULL, type VARCHAR(20) NOT NULL, instruction TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E30866EFF77FB932 ON protocole_etape (protocole_id)');
        $this->addSql('ALTER TABLE protocole_etape ADD CONSTRAINT FK_PROTOCOLE_ETAPE_PROTOCOLE FOREIGN KEY (protocole_id) REFERENCES protocole_premiers_gestes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE protocole_etape'); $this->addSql('DROP TABLE protocole_premiers_gestes'); }
}
