<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Alignement des noms d'index et séquence Avis avec les conventions Doctrine.
 * Renomme les index créés manuellement vers les noms attendus par l'ORM.
 */
final class Version20260702122044 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Alignement conventions Doctrine : renommage index table avis et user, séquence IDENTITY.';
    }

    public function up(Schema $schema): void
    {
        // Passer la séquence avis.id en IDENTITY (convention PostgreSQL Doctrine)
        $this->addSql('ALTER TABLE avis ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE avis ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');

        // Supprimer l'index signale créé manuellement (Doctrine le recrée à sa façon si besoin)
        $this->addSql('DROP INDEX IF EXISTS idx_avis_signale');

        // Aligner les noms d'index aux conventions Doctrine (hash sur le nom de table + colonne)
        $this->addSql('ALTER INDEX IF EXISTS idx_avis_patient RENAME TO IDX_8F91ABF06B899279');
        $this->addSql('ALTER INDEX IF EXISTS idx_avis_medecin RENAME TO IDX_8F91ABF04F31A84');
        $this->addSql('ALTER INDEX IF EXISTS uq_avis_patient_medecin RENAME TO unique_avis_patient_medecin');

        // Aligner les noms d'index uniques sur la table user
        $this->addSql('ALTER INDEX IF EXISTS uniq_email_verification_token RENAME TO UNIQ_8D93D649C4995C67');
        $this->addSql('ALTER INDEX IF EXISTS uniq_password_reset_token RENAME TO UNIQ_8D93D6496B7BA4B6');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE avis ALTER id SET DEFAULT nextval(\'avis_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE avis ALTER id DROP IDENTITY');

        $this->addSql('CREATE INDEX idx_avis_signale ON avis (signale)');

        $this->addSql('ALTER INDEX IF EXISTS IDX_8F91ABF06B899279 RENAME TO idx_avis_patient');
        $this->addSql('ALTER INDEX IF EXISTS IDX_8F91ABF04F31A84 RENAME TO idx_avis_medecin');
        $this->addSql('ALTER INDEX IF EXISTS unique_avis_patient_medecin RENAME TO uq_avis_patient_medecin');
        $this->addSql('ALTER INDEX IF EXISTS UNIQ_8D93D649C4995C67 RENAME TO uniq_email_verification_token');
        $this->addSql('ALTER INDEX IF EXISTS UNIQ_8D93D6496B7BA4B6 RENAME TO uniq_password_reset_token');
    }
}
