<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260710145130 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, dernier_message_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A8E26E95928F487 ON conversation (dernier_message_id)');
        $this->addSql('CREATE TABLE conversation_participants (conversation_id INT NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (conversation_id, user_id))');
        $this->addSql('CREATE INDEX IDX_21821ED39AC0396 ON conversation_participants (conversation_id)');
        $this->addSql('CREATE INDEX IDX_21821ED3A76ED395 ON conversation_participants (user_id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E95928F487 FOREIGN KEY (dernier_message_id) REFERENCES message (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED39AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT fk_b6bd307fa4f84f6e');
        $this->addSql('DROP INDEX idx_b6bd307fa4f84f6e');
        $this->addSql('ALTER TABLE message ADD statut VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE message ADD type_message VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE message ADD duree_voix INT DEFAULT NULL');
        $this->addSql('ALTER TABLE message ADD modifie_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE message ADD est_transfere BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE message ADD supprime_pour_expediteur BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE message ADD supprime_pour_destinataire BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE message ADD conversation_id INT NOT NULL');
        $this->addSql('ALTER TABLE message ADD media_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE message ADD message_parent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE message ADD est_modifie BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE message DROP is_read');
        $this->addSql('ALTER TABLE message DROP destinataire_id');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FEA9FDD75 FOREIGN KEY (media_id) REFERENCES media_object (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F18C3CC46 FOREIGN KEY (message_parent_id) REFERENCES message (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FEA9FDD75 ON message (media_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F18C3CC46 ON message (message_parent_id)');
        $this->addSql('ALTER TABLE "user" ADD est_en_ligne BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD derniere_presence TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E95928F487');
        $this->addSql('ALTER TABLE conversation_participants DROP CONSTRAINT FK_21821ED39AC0396');
        $this->addSql('ALTER TABLE conversation_participants DROP CONSTRAINT FK_21821ED3A76ED395');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE conversation_participants');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FEA9FDD75');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F18C3CC46');
        $this->addSql('DROP INDEX IDX_B6BD307F9AC0396');
        $this->addSql('DROP INDEX IDX_B6BD307FEA9FDD75');
        $this->addSql('DROP INDEX IDX_B6BD307F18C3CC46');
        $this->addSql('ALTER TABLE message ADD destinataire_id UUID NOT NULL');
        $this->addSql('ALTER TABLE message ADD is_read BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE message DROP statut');
        $this->addSql('ALTER TABLE message DROP type_message');
        $this->addSql('ALTER TABLE message DROP duree_voix');
        $this->addSql('ALTER TABLE message DROP est_modifie');
        $this->addSql('ALTER TABLE message DROP modifie_at');
        $this->addSql('ALTER TABLE message DROP est_transfere');
        $this->addSql('ALTER TABLE message DROP supprime_pour_expediteur');
        $this->addSql('ALTER TABLE message DROP supprime_pour_destinataire');
        $this->addSql('ALTER TABLE message DROP conversation_id');
        $this->addSql('ALTER TABLE message DROP media_id');
        $this->addSql('ALTER TABLE message DROP message_parent_id');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT fk_b6bd307fa4f84f6e FOREIGN KEY (destinataire_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_b6bd307fa4f84f6e ON message (destinataire_id)');
        $this->addSql('ALTER TABLE "user" DROP est_en_ligne');
        $this->addSql('ALTER TABLE "user" DROP derniere_presence');
    }
}
