<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260808120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les signalements privés effectués par les patients envers les médecins.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE signalement_medecin (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            patient_id UUID NOT NULL,
            medecin_id UUID NOT NULL,
            motif VARCHAR(80) NOT NULL,
            description TEXT NOT NULL,
            statut VARCHAR(30) NOT NULL,
            note_admin TEXT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            traite_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_E5721B326B899279 ON signalement_medecin (patient_id)');
        $this->addSql('CREATE INDEX IDX_E5721B324F31A84 ON signalement_medecin (medecin_id)');
        $this->addSql('CREATE INDEX idx_signalement_patient_medecin_statut ON signalement_medecin (patient_id, medecin_id, statut)');
        $this->addSql('CREATE INDEX idx_signalement_statut_created ON signalement_medecin (statut, created_at)');
        $this->addSql('ALTER TABLE signalement_medecin ADD CONSTRAINT FK_SIGNALEMENT_PATIENT FOREIGN KEY (patient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE signalement_medecin ADD CONSTRAINT FK_SIGNALEMENT_MEDECIN FOREIGN KEY (medecin_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE signalement_medecin');
    }
}
