<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261008120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Workflow SOS complet : cible, preuve caméra, vérification/sirène, prise en charge habilitée, traçabilité (sos_trace)';
    }

    public function up(Schema $schema): void
    {
        // ── demande_sos : nouveau cycle de vie ─────────────────────────────
        $this->addSql('ALTER TABLE demande_sos ADD etablissement_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_sos ADD verifie_par_id UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_sos ADD verifie_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_sos ADD verification_comment TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_sos ADD pris_en_charge_par_id UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_sos ADD pris_en_charge_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_sos ADD resolu_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_sos ADD sirene_active BOOLEAN DEFAULT \'false\' NOT NULL');
        $this->addSql('ALTER TABLE demande_sos ADD preuve_photo TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_sos ADD suivi_token VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_sos ADD CONSTRAINT FK_SOS_ETABLISSEMENT FOREIGN KEY (etablissement_id) REFERENCES centre_de_sante (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE demande_sos ADD CONSTRAINT FK_SOS_VERIFIE_PAR FOREIGN KEY (verifie_par_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE demande_sos ADD CONSTRAINT FK_SOS_PRIS_EN_CHARGE_PAR FOREIGN KEY (pris_en_charge_par_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_SOS_ETABLISSEMENT ON demande_sos (etablissement_id)');
        $this->addSql('CREATE INDEX IDX_SOS_STATUT_ETABLISSEMENT ON demande_sos (statut, etablissement_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SOS_SUIVI_TOKEN ON demande_sos (suivi_token)');

        // ── sos_trace : journal d'audit immuable ───────────────────────────
        $this->addSql('CREATE TABLE sos_trace (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
            sos_id INT NOT NULL,
            action VARCHAR(40) NOT NULL,
            auteur_id UUID DEFAULT NULL,
            details JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
        )');
        $this->addSql('CREATE INDEX IDX_SOS_TRACE_SOS ON sos_trace (sos_id)');
        $this->addSql('CREATE INDEX IDX_SOS_TRACE_CREATED ON sos_trace (created_at)');
        $this->addSql('ALTER TABLE sos_trace ADD CONSTRAINT FK_SOS_TRACE_SOS FOREIGN KEY (sos_id) REFERENCES demande_sos (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sos_trace ADD CONSTRAINT FK_SOS_TRACE_AUTEUR FOREIGN KEY (auteur_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sos_trace');
        $this->addSql('DROP INDEX UNIQ_SOS_SUIVI_TOKEN');
        $this->addSql('DROP INDEX IDX_SOS_STATUT_ETABLISSEMENT');
        $this->addSql('DROP INDEX IDX_SOS_ETABLISSEMENT');
        $this->addSql('ALTER TABLE demande_sos DROP CONSTRAINT FK_SOS_PRIS_EN_CHARGE_PAR');
        $this->addSql('ALTER TABLE demande_sos DROP CONSTRAINT FK_SOS_VERIFIE_PAR');
        $this->addSql('ALTER TABLE demande_sos DROP CONSTRAINT FK_SOS_ETABLISSEMENT');
        $this->addSql('ALTER TABLE demande_sos DROP suivi_token');
        $this->addSql('ALTER TABLE demande_sos DROP preuve_photo');
        $this->addSql('ALTER TABLE demande_sos DROP sirene_active');
        $this->addSql('ALTER TABLE demande_sos DROP resolu_at');
        $this->addSql('ALTER TABLE demande_sos DROP pris_en_charge_at');
        $this->addSql('ALTER TABLE demande_sos DROP pris_en_charge_par_id');
        $this->addSql('ALTER TABLE demande_sos DROP verification_comment');
        $this->addSql('ALTER TABLE demande_sos DROP verifie_at');
        $this->addSql('ALTER TABLE demande_sos DROP verifie_par_id');
        $this->addSql('ALTER TABLE demande_sos DROP etablissement_id');
    }
}
