<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260814160734 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Structure les médicaments des prescriptions sans perdre les données historiques';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE prescription_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, posologie VARCHAR(255) NOT NULL, duree VARCHAR(100) DEFAULT NULL, forme VARCHAR(100) DEFAULT NULL, dosage DOUBLE PRECISION DEFAULT NULL, unite VARCHAR(50) DEFAULT NULL, voie_administration VARCHAR(100) DEFAULT NULL, frequence VARCHAR(100) DEFAULT NULL, moment_prise VARCHAR(100) DEFAULT NULL, duree_jours INT DEFAULT NULL, quantite DOUBLE PRECISION DEFAULT NULL, instructions TEXT DEFAULT NULL, si_besoin BOOLEAN DEFAULT false NOT NULL, prescription_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1D4599EB93DB413D ON prescription_item (prescription_id)');
        $this->addSql('ALTER TABLE prescription_item ADD CONSTRAINT FK_1D4599EB93DB413D FOREIGN KEY (prescription_id) REFERENCES prescription (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql(<<<'SQL'
            INSERT INTO prescription_item (
                prescription_id, nom, posologie, duree, forme, dosage, unite,
                voie_administration, frequence, moment_prise, duree_jours,
                quantite, instructions, si_besoin
            )
            SELECT
                p.id,
                COALESCE(NULLIF(item->>'nom', ''), 'Médicament non renseigné'),
                COALESCE(NULLIF(item->>'posologie', ''), 'À préciser'),
                NULLIF(item->>'duree', ''),
                NULLIF(item->>'forme', ''),
                CASE WHEN COALESCE(item->>'dosage', '') ~ '^[0-9]+([.][0-9]+)?$'
                     THEN (item->>'dosage')::DOUBLE PRECISION ELSE NULL END,
                NULLIF(item->>'unite', ''),
                NULLIF(item->>'voieAdministration', ''),
                NULLIF(item->>'frequence', ''),
                NULLIF(item->>'momentPrise', ''),
                CASE WHEN COALESCE(item->>'dureeJours', '') ~ '^[0-9]+$'
                     THEN (item->>'dureeJours')::INT ELSE NULL END,
                CASE WHEN COALESCE(item->>'quantite', '') ~ '^[0-9]+([.][0-9]+)?$'
                     THEN (item->>'quantite')::DOUBLE PRECISION ELSE NULL END,
                NULLIF(item->>'instructions', ''),
                COALESCE((item->>'siBesoin')::BOOLEAN, false)
            FROM prescription p
            CROSS JOIN LATERAL jsonb_array_elements(
                CASE WHEN jsonb_typeof(p.medicaments::jsonb) = 'array'
                     THEN p.medicaments::jsonb ELSE '[]'::jsonb END
            ) AS item
        SQL);
        $this->addSql('ALTER TABLE prescription DROP medicaments');
        $this->addSql('ALTER TABLE prescription ALTER statut SET DEFAULT \'BROUILLON\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE prescription_item DROP CONSTRAINT FK_1D4599EB93DB413D');
        $this->addSql('ALTER TABLE prescription ADD medicaments JSON NOT NULL');
        $this->addSql(<<<'SQL'
            UPDATE prescription p
            SET medicaments = COALESCE(
                (
                    SELECT json_agg(json_build_object(
                        'nom', i.nom, 'posologie', i.posologie, 'duree', i.duree,
                        'forme', i.forme, 'dosage', i.dosage, 'unite', i.unite,
                        'voieAdministration', i.voie_administration,
                        'frequence', i.frequence, 'momentPrise', i.moment_prise,
                        'dureeJours', i.duree_jours, 'quantite', i.quantite,
                        'instructions', i.instructions, 'siBesoin', i.si_besoin
                    ))
                    FROM prescription_item i WHERE i.prescription_id = p.id
                ), '[]'::json
            )
        SQL);
        $this->addSql('DROP TABLE prescription_item');
        $this->addSql('ALTER TABLE prescription ALTER statut DROP DEFAULT');
    }
}
