<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Module "Carte Santé" : enrichissement des centres de santé + tables métiers
 * (avis établissement, suggestions d'édition, affiliations médecins, demandes SOS,
 *  équipes dirigées par établissement / niveaux d'accès).
 */
final class Version20260917120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Module Carte Santé : avis_etablissement, suggestion_etablissement, affiliation_medecin, demande_sos, etablissement_equipe + enrichissement centre_de_sante.';
    }

    public function up(Schema $schema): void
    {
        // ── Enrichissement centre_de_sante ─────────────────────────────
        $this->addSql('ALTER TABLE centre_de_sante ADD note_moyenne DOUBLE PRECISION NOT NULL DEFAULT 0');
        $this->addSql('ALTER TABLE centre_de_sante ADD total_avis INT NOT NULL DEFAULT 0');
        $this->addSql('ALTER TABLE centre_de_sante ADD google_place_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE centre_de_sante ADD verification_statut VARCHAR(30) DEFAULT \'NON_VERIFIE\' NOT NULL');

        // ── avis_etablissement ──────────────────────────────────────────
        $this->addSql('CREATE TABLE avis_etablissement (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
            etablissement_id INT NOT NULL,
            user_id UUID DEFAULT NULL,
            note SMALLINT NOT NULL,
            commentaire TEXT DEFAULT NULL,
            statut VARCHAR(20) DEFAULT \'PUBLIE\' NOT NULL,
            signale BOOLEAN DEFAULT false NOT NULL,
            raison_signalement TEXT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
        )');
        $this->addSql('CREATE INDEX IDX_AVIS_ETAB_ETABLISSEMENT ON avis_etablissement (etablissement_id)');
        $this->addSql('CREATE INDEX IDX_AVIS_ETAB_ETABLISSEMENT_STATUT ON avis_etablissement (etablissement_id, statut)');
        $this->addSql('ALTER TABLE avis_etablissement ADD CONSTRAINT FK_AVIS_ETABLISSEMENT FOREIGN KEY (etablissement_id) REFERENCES centre_de_sante (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE avis_etablissement ADD CONSTRAINT FK_AVIS_ETAB_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── suggestion_etablissement ────────────────────────────────────
        $this->addSql('CREATE TABLE suggestion_etablissement (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
            etablissement_id INT NOT NULL,
            user_id UUID DEFAULT NULL,
            champ VARCHAR(100) NOT NULL,
            valeur_proposee TEXT NOT NULL,
            commentaire TEXT DEFAULT NULL,
            statut VARCHAR(20) DEFAULT \'EN_ATTENTE\' NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
        )');
        $this->addSql('CREATE INDEX IDX_SUGG_ETAB_ETABLISSEMENT ON suggestion_etablissement (etablissement_id)');
        $this->addSql('CREATE INDEX IDX_SUGG_ETAB_STATUT ON suggestion_etablissement (statut)');
        $this->addSql('ALTER TABLE suggestion_etablissement ADD CONSTRAINT FK_SUGG_ETABLISSEMENT FOREIGN KEY (etablissement_id) REFERENCES centre_de_sante (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE suggestion_etablissement ADD CONSTRAINT FK_SUGG_ETAB_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── affiliation_medecin ─────────────────────────────────────────
        $this->addSql('CREATE TABLE affiliation_medecin (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
            medecin_id UUID NOT NULL,
            etablissement_id INT NOT NULL,
            fonction VARCHAR(255) DEFAULT NULL,
            salle VARCHAR(120) DEFAULT NULL,
            planning JSON DEFAULT NULL,
            teleconsultation BOOLEAN DEFAULT false NOT NULL,
            statut VARCHAR(20) DEFAULT \'EN_ATTENTE\' NOT NULL,
            created_by_id UUID DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
        )');
        $this->addSql('CREATE INDEX IDX_AFF_MEDECIN_MEDECIN ON affiliation_medecin (medecin_id)');
        $this->addSql('CREATE INDEX IDX_AFF_MEDECIN_ETABLISSEMENT ON affiliation_medecin (etablissement_id)');
        $this->addSql('CREATE INDEX IDX_AFF_MEDECIN_STATUT ON affiliation_medecin (statut, etablissement_id)');
        $this->addSql('ALTER TABLE affiliation_medecin ADD CONSTRAINT FK_AFF_MEDECIN FOREIGN KEY (medecin_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE affiliation_medecin ADD CONSTRAINT FK_AFF_ETABLISSEMENT FOREIGN KEY (etablissement_id) REFERENCES centre_de_sante (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE affiliation_medecin ADD CONSTRAINT FK_AFF_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── demande_sos ─────────────────────────────────────────────────
        $this->addSql('CREATE TABLE demande_sos (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
            user_id UUID DEFAULT NULL,
            nom VARCHAR(255) DEFAULT NULL,
            telephone VARCHAR(255) DEFAULT NULL,
            latitude DOUBLE PRECISION NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            description TEXT DEFAULT NULL,
            statut VARCHAR(20) DEFAULT \'EN_COURS\' NOT NULL,
            proches JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
        )');
        $this->addSql('CREATE INDEX IDX_SOS_USER ON demande_sos (user_id)');
        $this->addSql('CREATE INDEX IDX_SOS_STATUT_CREATED ON demande_sos (statut, created_at)');
        $this->addSql('ALTER TABLE demande_sos ADD CONSTRAINT FK_SOS_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── etablissement_equipe ────────────────────────────────────────
        $this->addSql('CREATE TABLE etablissement_equipe (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
            etablissement_id INT NOT NULL,
            user_id UUID NOT NULL,
            role VARCHAR(30) NOT NULL,
            statut VARCHAR(20) DEFAULT \'INVITE\' NOT NULL,
            invite_par_id UUID DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
        )');
        $this->addSql('CREATE INDEX IDX_EQUIPE_ETABLISSEMENT ON etablissement_equipe (etablissement_id)');
        $this->addSql('CREATE INDEX IDX_EQUIPE_USER ON etablissement_equipe (user_id)');
        $this->addSql('CREATE INDEX IDX_EQUIPE_ACTIF_ROLE ON etablissement_equipe (etablissement_id, statut, role)');
        $this->addSql('ALTER TABLE etablissement_equipe ADD CONSTRAINT FK_EQUIPE_ETABLISSEMENT FOREIGN KEY (etablissement_id) REFERENCES centre_de_sante (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE etablissement_equipe ADD CONSTRAINT FK_EQUIPE_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE etablissement_equipe ADD CONSTRAINT FK_EQUIPE_INVITE_PAR FOREIGN KEY (invite_par_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE avis_etablissement DROP CONSTRAINT FK_AVIS_ETAB_USER');
        $this->addSql('ALTER TABLE avis_etablissement DROP CONSTRAINT FK_AVIS_ETABLISSEMENT');
        $this->addSql('ALTER TABLE suggestion_etablissement DROP CONSTRAINT FK_SUGG_ETAB_USER');
        $this->addSql('ALTER TABLE suggestion_etablissement DROP CONSTRAINT FK_SUGG_ETABLISSEMENT');
        $this->addSql('ALTER TABLE affiliation_medecin DROP CONSTRAINT FK_AFF_CREATED_BY');
        $this->addSql('ALTER TABLE affiliation_medecin DROP CONSTRAINT FK_AFF_ETABLISSEMENT');
        $this->addSql('ALTER TABLE affiliation_medecin DROP CONSTRAINT FK_AFF_MEDECIN');
        $this->addSql('ALTER TABLE demande_sos DROP CONSTRAINT FK_SOS_USER');
        $this->addSql('ALTER TABLE etablissement_equipe DROP CONSTRAINT FK_EQUIPE_INVITE_PAR');
        $this->addSql('ALTER TABLE etablissement_equipe DROP CONSTRAINT FK_EQUIPE_USER');
        $this->addSql('ALTER TABLE etablissement_equipe DROP CONSTRAINT FK_EQUIPE_ETABLISSEMENT');

        $this->addSql('DROP TABLE etablissement_equipe');
        $this->addSql('DROP TABLE demande_sos');
        $this->addSql('DROP TABLE affiliation_medecin');
        $this->addSql('DROP TABLE suggestion_etablissement');
        $this->addSql('DROP TABLE avis_etablissement');

        $this->addSql('ALTER TABLE centre_de_sante DROP verification_statut');
        $this->addSql('ALTER TABLE centre_de_sante DROP google_place_id');
        $this->addSql('ALTER TABLE centre_de_sante DROP total_avis');
        $this->addSql('ALTER TABLE centre_de_sante DROP note_moyenne');
    }
}