<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260731143000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les tables de symptomes structures pour le moteur de triage.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS symptome (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, synonymes JSON DEFAULT NULL, ordre INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_symptome_slug ON symptome (slug)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_symptome_nom ON symptome (nom)');
        $this->addSql('CREATE TABLE IF NOT EXISTS maladie_symptome (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, maladie_id INT NOT NULL, symptome_id INT NOT NULL, poids INT NOT NULL, frequence VARCHAR(40) DEFAULT NULL, obligatoire BOOLEAN NOT NULL DEFAULT false, contradictoire BOOLEAN NOT NULL DEFAULT false, gravite VARCHAR(40) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_maladie_symptome_pair ON maladie_symptome (maladie_id, symptome_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_maladie_symptome_maladie ON maladie_symptome (maladie_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_maladie_symptome_symptome ON maladie_symptome (symptome_id)');
        $this->addSql('ALTER TABLE maladie_symptome ADD CONSTRAINT fk_maladie_symptome_maladie FOREIGN KEY (maladie_id) REFERENCES maladie (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maladie_symptome ADD CONSTRAINT fk_maladie_symptome_symptome FOREIGN KEY (symptome_id) REFERENCES symptome (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS maladie_symptome');
        $this->addSql('DROP TABLE IF EXISTS symptome');
    }
}
