<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260630143000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add consultations and link messages to conversations.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE consultation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, patient_id UUID NOT NULL, medecin_id UUID NOT NULL, statut VARCHAR(30) NOT NULL, motif VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9646858B6B899279 ON consultation (patient_id)');
        $this->addSql('CREATE INDEX IDX_9646858B3F71D4B9 ON consultation (medecin_id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_9646858B6B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_9646858B3F71D4B9 FOREIGN KEY (medecin_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD consultation_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_B6BD307F8657B4D2 ON message (consultation_id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F8657B4D2 FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F8657B4D2');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_9646858B6B899279');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_9646858B3F71D4B9');
        $this->addSql('DROP TABLE consultation');
        $this->addSql('DROP INDEX IDX_B6BD307F8657B4D2');
        $this->addSql('ALTER TABLE message DROP consultation_id');
    }
}
