<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260803120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Observabilite des premiers gestes : journal des versions consultees et statistiques anonymes de recherche.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE protocole_consultation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(120) NOT NULL, version VARCHAR(40) NOT NULL, consulted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_protocole_consultation_date ON protocole_consultation (consulted_at)');
        $this->addSql('CREATE TABLE protocole_recherche_stat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stat_date DATE NOT NULL, total_count INT NOT NULL, with_result_count INT NOT NULL, without_result_count INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_protocole_recherche_stat_date ON protocole_recherche_stat (stat_date)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE protocole_recherche_stat');
        $this->addSql('DROP TABLE protocole_consultation');
    }
}
