-- ============================================================================
-- MediSecours+ — PostgreSQL schema (final state)
-- Reconstructed from all 55 Doctrine migrations in medisecours-backend/migrations
-- Aim: a single fresh, standalone Postgres schema for any provider
--       (Coolify self-hosted PostgreSQL 16, Neon, Supabase, local psql).
-- MySQL is NOT supported — this project is PostgreSQL only.
--
-- Apply order (fresh database):
--   psql "$DATABASE_URL" -f database/schema.sql
--   psql "$DATABASE_URL" -f database/seed.sql
--
-- Then let the backend bootstrap symptom/protocol reference data on first
-- boot (BOOTSTRAP_REFERENCE_DATA=1) — see DEPLOYMENT.md.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ===========================================================================
-- PART 1 — TABLES (+ indexes), no foreign keys yet.
-- Foreign keys are added in PART 2 so circular references work.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. USER   (single-table inheritance: patient / medecin / admin)
-- ---------------------------------------------------------------------------
CREATE TABLE "user" (
    id UUID NOT NULL PRIMARY KEY,
    email VARCHAR(180) NOT NULL,
    roles JSON NOT NULL,
    password VARCHAR(255) NOT NULL,
    nom VARCHAR(255) DEFAULT NULL,
    prenom VARCHAR(255) DEFAULT NULL,
    telephone VARCHAR(255) DEFAULT NULL,
    quartier VARCHAR(255) DEFAULT NULL,
    photo_profil VARCHAR(255) DEFAULT NULL,
    type VARCHAR(255) NOT NULL,
    groupe_sanguin VARCHAR(10) DEFAULT NULL,
    allergies JSON DEFAULT NULL,
    contacts_urgence JSON DEFAULT NULL,
    specialite VARCHAR(255) DEFAULT NULL,
    numero_ordre VARCHAR(100) DEFAULT NULL,
    est_valide BOOLEAN DEFAULT false,
    disponibilites JSON DEFAULT NULL,
    disponibilites_texte TEXT DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    est_en_ligne BOOLEAN DEFAULT false NOT NULL,
    derniere_presence TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    actif BOOLEAN DEFAULT true NOT NULL,
    banni BOOLEAN DEFAULT false NOT NULL,
    email_verified BOOLEAN DEFAULT false NOT NULL,
    email_verification_token VARCHAR(100) DEFAULT NULL,
    email_verification_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    password_reset_token VARCHAR(100) DEFAULT NULL,
    password_reset_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    type_piece_identite VARCHAR(20) DEFAULT NULL,
    piece_identite_id INT DEFAULT NULL,
    piece_identite_verso_id INT DEFAULT NULL,
    photo_verification_identite_id INT DEFAULT NULL
);

CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email);
CREATE UNIQUE INDEX UNIQ_8D93D649C4995C67 ON "user" (email_verification_token);
CREATE UNIQUE INDEX UNIQ_8D93D6496B7BA4B6 ON "user" (password_reset_token);
CREATE INDEX IDX_8D93D6491B21CC5E ON "user" (piece_identite_id);
CREATE INDEX IDX_8D93D649A26FACA5 ON "user" (piece_identite_verso_id);
CREATE INDEX IDX_8D93D64992F2B792 ON "user" (photo_verification_identite_id);

-- ---------------------------------------------------------------------------
-- 2. MEDIA OBJECT   (uploads via VichUploader: photos, scans, voice, …)
-- ---------------------------------------------------------------------------
CREATE TABLE media_object (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    file_path VARCHAR(255) DEFAULT NULL,
    original_name VARCHAR(255) DEFAULT NULL,
    mime_type VARCHAR(100) DEFAULT NULL,
    size INT DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    uploaded_by_id UUID DEFAULT NULL,
    centre_id INT DEFAULT NULL,
    categorie_id INT DEFAULT NULL,
    maladie_id INT DEFAULT NULL,
    is_public BOOLEAN DEFAULT true NOT NULL,
    data TEXT DEFAULT NULL,
    purpose VARCHAR(40) DEFAULT 'general' NOT NULL
);

CREATE INDEX IDX_14D43132A2B28FE8 ON media_object (uploaded_by_id);
CREATE INDEX IDX_14D43132463CD7C3 ON media_object (centre_id);
CREATE INDEX IDX_14D43132BCF5E72D ON media_object (categorie_id);
CREATE INDEX IDX_14D43132B4B1C397 ON media_object (maladie_id);

-- ---------------------------------------------------------------------------
-- 3. CATEGORIE   (disease catalog categories)
-- ---------------------------------------------------------------------------
CREATE TABLE categorie (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    nom_en VARCHAR(255) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    description_en TEXT DEFAULT NULL,
    couleur VARCHAR(7) DEFAULT NULL,
    icone VARCHAR(100) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
);

-- ---------------------------------------------------------------------------
-- 4. CENTRE DE SANTE
-- ---------------------------------------------------------------------------
CREATE TABLE centre_de_sante (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    adresse VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    telephone VARCHAR(255) DEFAULT NULL,
    horaires VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    ville VARCHAR(100) NOT NULL,
    region VARCHAR(100) NOT NULL,
    specialites JSON NOT NULL,
    services JSON NOT NULL,
    description TEXT DEFAULT NULL,
    est_actif BOOLEAN NOT NULL,
    urgences24h BOOLEAN NOT NULL,
    email VARCHAR(255) DEFAULT NULL,
    site_web VARCHAR(255) DEFAULT NULL,
    statut VARCHAR(50) DEFAULT 'prive' NOT NULL,
    quartier VARCHAR(255) DEFAULT NULL,
    image_url VARCHAR(500) DEFAULT NULL,
    note_moyenne DOUBLE PRECISION DEFAULT 0 NOT NULL,
    total_avis INT DEFAULT 0 NOT NULL,
    google_place_id VARCHAR(255) DEFAULT NULL,
    verification_statut VARCHAR(30) DEFAULT 'NON_VERIFIE' NOT NULL
);

-- ---------------------------------------------------------------------------
-- 5. MALADIE
-- ---------------------------------------------------------------------------
CREATE TABLE maladie (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    nom_en VARCHAR(255) DEFAULT NULL,
    description TEXT NOT NULL,
    description_en TEXT DEFAULT NULL,
    symptomes TEXT DEFAULT NULL,
    symptomes_en TEXT DEFAULT NULL,
    precautions TEXT DEFAULT NULL,
    precautions_en TEXT DEFAULT NULL,
    traitement TEXT DEFAULT NULL,
    traitement_en TEXT DEFAULT NULL,
    niveau_gravite VARCHAR(50) NOT NULL,
    contagieux BOOLEAN DEFAULT NULL,
    urgence BOOLEAN DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    causes TEXT DEFAULT NULL,
    causes_en TEXT DEFAULT NULL,
    is_accident BOOLEAN DEFAULT NULL,
    type_accident VARCHAR(255) DEFAULT NULL,
    type_accident_en VARCHAR(255) DEFAULT NULL,
    image_url VARCHAR(500) DEFAULT NULL,
    patient_visible BOOLEAN DEFAULT false NOT NULL,
    patient_priority INT DEFAULT NULL,
    categorie_id INT NOT NULL
);

CREATE INDEX IDX_ADC4024BBCF5E72D ON maladie (categorie_id);
CREATE INDEX idx_maladie_patient_catalogue ON maladie (patient_visible, patient_priority);

-- ---------------------------------------------------------------------------
-- 6. PREMIER SOIN   (first-aid sheets linked to a maladie)
-- ---------------------------------------------------------------------------
CREATE TABLE premier_soin (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    titre VARCHAR(255) NOT NULL,
    titre_en VARCHAR(255) DEFAULT NULL,
    description TEXT NOT NULL,
    description_en TEXT DEFAULT NULL,
    symptomes TEXT DEFAULT NULL,
    symptomes_en TEXT DEFAULT NULL,
    niveau_urgence VARCHAR(50) NOT NULL,
    maladie_id INT DEFAULT NULL
);

CREATE INDEX IDX_AD8436B2B4B1C397 ON premier_soin (maladie_id);

-- ---------------------------------------------------------------------------
-- 7. CONSULTATION
-- ---------------------------------------------------------------------------
CREATE TABLE consultation (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    patient_id UUID NOT NULL,
    medecin_id UUID DEFAULT NULL,
    statut VARCHAR(30) NOT NULL,
    motif VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    date_consultation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    priorite VARCHAR(20) DEFAULT 'NORMALE' NOT NULL,
    compte_rendu TEXT DEFAULT NULL
);

CREATE INDEX IDX_964685A66B899279 ON consultation (patient_id);
CREATE INDEX IDX_964685A64F31A84 ON consultation (medecin_id);

-- ---------------------------------------------------------------------------
-- 8. CONVERSATION + participants
-- ---------------------------------------------------------------------------
CREATE TABLE conversation (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    titre VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    dernier_message_id INT DEFAULT NULL,
    pair_key VARCHAR(73) DEFAULT NULL
);

CREATE UNIQUE INDEX UNIQ_8A8E26E9AEE589DA ON conversation (pair_key);
CREATE INDEX IDX_8A8E26E95928F487 ON conversation (dernier_message_id);

CREATE TABLE conversation_participants (
    conversation_id INT NOT NULL,
    user_id UUID NOT NULL,
    PRIMARY KEY (conversation_id, user_id)
);

CREATE INDEX IDX_21821ED39AC0396 ON conversation_participants (conversation_id);
CREATE INDEX IDX_21821ED3A76ED395 ON conversation_participants (user_id);

-- ---------------------------------------------------------------------------
-- 9. MESSAGE
-- ---------------------------------------------------------------------------
CREATE TABLE message (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    contenu TEXT NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    expediteur_id UUID NOT NULL,
    deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    consultation_id INT DEFAULT NULL,
    statut VARCHAR(20) NOT NULL,
    type_message VARCHAR(20) NOT NULL,
    duree_voix INT DEFAULT NULL,
    modifie_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    est_transfere BOOLEAN DEFAULT false NOT NULL,
    supprime_pour_expediteur BOOLEAN DEFAULT false NOT NULL,
    supprime_pour_destinataire BOOLEAN DEFAULT false NOT NULL,
    conversation_id INT NOT NULL,
    media_id INT DEFAULT NULL,
    message_parent_id INT DEFAULT NULL,
    est_modifie BOOLEAN DEFAULT false NOT NULL
);

CREATE INDEX IDX_B6BD307F10335F61 ON message (expediteur_id);
CREATE INDEX IDX_B6BD307F62FF6CDF ON message (consultation_id);
CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id);
CREATE INDEX IDX_B6BD307FEA9FDD75 ON message (media_id);
CREATE INDEX IDX_B6BD307F18C3CC46 ON message (message_parent_id);

-- ---------------------------------------------------------------------------
-- 10. AVIS
-- ---------------------------------------------------------------------------
CREATE TABLE avis (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    patient_id UUID NOT NULL,
    medecin_id UUID NOT NULL,
    note SMALLINT NOT NULL,
    commentaire TEXT DEFAULT NULL,
    signale BOOLEAN DEFAULT false NOT NULL,
    raison_signalement TEXT DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
);

CREATE INDEX IDX_8F91ABF06B899279 ON avis (patient_id);
CREATE INDEX IDX_8F91ABF04F31A84 ON avis (medecin_id);
CREATE INDEX idx_avis_signale ON avis (signale);

-- ---------------------------------------------------------------------------
-- 11. PRESCRIPTION + prescription_item
-- ---------------------------------------------------------------------------
CREATE TABLE prescription (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    diagnostic TEXT NOT NULL,
    recommandations TEXT DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    consultation_id INT NOT NULL,
    medecin_id UUID NOT NULL,
    patient_id UUID NOT NULL,
    reference VARCHAR(40) NOT NULL,
    statut VARCHAR(20) DEFAULT 'BROUILLON' NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    cancel_reason TEXT DEFAULT NULL,
    sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    version INT DEFAULT 1 NOT NULL,
    superseded_by_id INT DEFAULT NULL
);

CREATE UNIQUE INDEX UNIQ_1FBFB8D9AEA34913 ON prescription (reference);
CREATE INDEX IDX_1FBFB8D962FF6CDF ON prescription (consultation_id);
CREATE INDEX IDX_1FBFB8D94F31A84 ON prescription (medecin_id);
CREATE INDEX IDX_1FBFB8D96B899279 ON prescription (patient_id);
CREATE INDEX IDX_1FBFB8D939626D86 ON prescription (superseded_by_id);

CREATE TABLE prescription_item (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    posologie VARCHAR(255) NOT NULL,
    duree VARCHAR(100) DEFAULT NULL,
    forme VARCHAR(100) DEFAULT NULL,
    dosage DOUBLE PRECISION DEFAULT NULL,
    unite VARCHAR(50) DEFAULT NULL,
    voie_administration VARCHAR(100) DEFAULT NULL,
    frequence VARCHAR(100) DEFAULT NULL,
    moment_prise VARCHAR(100) DEFAULT NULL,
    duree_jours INT DEFAULT NULL,
    quantite DOUBLE PRECISION DEFAULT NULL,
    instructions TEXT DEFAULT NULL,
    si_besoin BOOLEAN DEFAULT false NOT NULL,
    prescription_id INT NOT NULL
);

CREATE INDEX IDX_1D4599EB93DB413D ON prescription_item (prescription_id);

-- ---------------------------------------------------------------------------
-- 12. SYMPTOME + maladie_symptome   (diagnostic engine)
-- ---------------------------------------------------------------------------
CREATE TABLE symptome (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nom VARCHAR(160) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    synonymes JSON DEFAULT NULL,
    ordre INT DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX UNIQ_241BF93A989D9B459 ON symptome (slug);

CREATE TABLE maladie_symptome (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    maladie_id INT NOT NULL,
    symptome_id INT NOT NULL,
    poids INT NOT NULL,
    frequence VARCHAR(40) DEFAULT NULL,
    obligatoire BOOLEAN NOT NULL,
    contradictoire BOOLEAN NOT NULL,
    gravite VARCHAR(40) DEFAULT NULL
);

CREATE UNIQUE INDEX UNIQ_941A7D2DA4E430F6 ON maladie_symptome (maladie_id, symptome_id);
CREATE INDEX IDX_941A7D2DB4B1C397 ON maladie_symptome (maladie_id);
CREATE INDEX IDX_941A7D2D12B83D77 ON maladie_symptome (symptome_id);

-- ---------------------------------------------------------------------------
-- 13. NOTIFICATION
-- ---------------------------------------------------------------------------
CREATE TABLE notification (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    recipient_id UUID NOT NULL,
    type VARCHAR(80) NOT NULL,
    title VARCHAR(160) NOT NULL,
    body VARCHAR(500) DEFAULT NULL,
    link VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
);

CREATE INDEX IDX_BF5476CAE92F8F78 ON notification (recipient_id);
CREATE INDEX idx_notification_recipient_read_created ON notification (recipient_id, read_at, created_at);

-- ---------------------------------------------------------------------------
-- 14. REFRESH TOKEN   (JWT refresh rotation)
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_token (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id UUID NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    family VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX UNIQ_C74F2195B3BC57DA ON refresh_token (token_hash);
CREATE INDEX idx_refresh_token_user_revoked ON refresh_token (user_id, revoked_at);

-- ---------------------------------------------------------------------------
-- 15. PROTOCOLES   (first-aid protocols / steps / consultation stats)
-- ---------------------------------------------------------------------------
CREATE TABLE protocole_premiers_gestes (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    slug VARCHAR(120) NOT NULL,
    titre VARCHAR(180) NOT NULL,
    titre_en VARCHAR(180) DEFAULT NULL,
    statut VARCHAR(20) NOT NULL,
    niveau_urgence VARCHAR(20) NOT NULL,
    population VARCHAR(20) NOT NULL,
    version VARCHAR(40) NOT NULL,
    source_clinique TEXT DEFAULT NULL,
    source_clinique_en TEXT DEFAULT NULL,
    categorie VARCHAR(60) DEFAULT NULL,
    restrictions_populations TEXT DEFAULT NULL,
    restrictions_populations_en TEXT DEFAULT NULL,
    master_slug VARCHAR(120) DEFAULT NULL,
    variant_key VARCHAR(40) DEFAULT NULL
);

CREATE UNIQUE INDEX uniq_protocole_slug_version ON protocole_premiers_gestes (slug, version);
CREATE INDEX idx_protocole_master_variant ON protocole_premiers_gestes (master_slug, variant_key);

CREATE TABLE protocole_etape (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    protocole_id INT NOT NULL,
    position INT NOT NULL,
    type VARCHAR(20) NOT NULL,
    instruction TEXT NOT NULL,
    instruction_en TEXT DEFAULT NULL,
    titre VARCHAR(160) DEFAULT NULL,
    titre_en VARCHAR(160) DEFAULT NULL
);

CREATE INDEX IDX_E30866EFF77FB932 ON protocole_etape (protocole_id);

CREATE TABLE protocole_consultation (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    slug VARCHAR(120) NOT NULL,
    version VARCHAR(40) NOT NULL,
    consulted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_protocole_consultation_date ON protocole_consultation (consulted_at);

CREATE TABLE protocole_recherche_stat (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    stat_date DATE NOT NULL,
    total_count INT NOT NULL,
    with_result_count INT NOT NULL,
    without_result_count INT NOT NULL
);

CREATE UNIQUE INDEX uniq_protocole_recherche_stat_date ON protocole_recherche_stat (stat_date);

-- ---------------------------------------------------------------------------
-- 16. SIGNALEMENT MEDECIN   (private patient → doctor reports)
-- ---------------------------------------------------------------------------
CREATE TABLE signalement_medecin (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    patient_id UUID NOT NULL,
    medecin_id UUID NOT NULL,
    motif VARCHAR(80) NOT NULL,
    description TEXT NOT NULL,
    statut VARCHAR(30) NOT NULL,
    note_admin TEXT DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    traite_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
);

CREATE INDEX IDX_E5721B326B899279 ON signalement_medecin (patient_id);
CREATE INDEX IDX_E5721B324F31A84 ON signalement_medecin (medecin_id);
CREATE INDEX idx_signalement_patient_medecin_statut ON signalement_medecin (patient_id, medecin_id, statut);
CREATE INDEX idx_signalement_statut_created ON signalement_medecin (statut, created_at);

-- ---------------------------------------------------------------------------
-- 17. REFERENCE DATA VERSION   (gate for idempotent bootstrap/seed commands)
-- ---------------------------------------------------------------------------
CREATE TABLE reference_data_version (
    dataset VARCHAR(100) NOT NULL PRIMARY KEY,
    catalog_version VARCHAR(80) NOT NULL,
    applied_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

-- ---------------------------------------------------------------------------
-- 18. GEDMO LOG ENTRIES   (doctrine extensions: loggable)
-- ---------------------------------------------------------------------------
CREATE TABLE ext_log_entries (
    id SERIAL NOT NULL PRIMARY KEY,
    action VARCHAR(8) NOT NULL,
    logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    object_id VARCHAR(64) DEFAULT NULL,
    object_class VARCHAR(255) NOT NULL,
    version INT NOT NULL,
    data TEXT DEFAULT NULL,
    username VARCHAR(255) DEFAULT NULL
);

CREATE INDEX log_class_lookup_idx ON ext_log_entries (object_class, object_id);
CREATE INDEX log_date_lookup_idx ON ext_log_entries (logged_at);
CREATE INDEX log_user_lookup_idx ON ext_log_entries (username);
CREATE INDEX log_version_lookup_idx ON ext_log_entries (object_id, object_class, version);

-- ---------------------------------------------------------------------------
-- 19. MESSENGER MESSAGES   (async queue — created by the doctrine transport)
-- ---------------------------------------------------------------------------
CREATE TABLE messenger_messages (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    body TEXT NOT NULL,
    headers TEXT NOT NULL,
    queue_name VARCHAR(190) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
);

CREATE INDEX IDX_1A8B4DA1E8F6E2C1 ON messenger_messages (queue_name, available_at);
CREATE INDEX IDX_1A8B4DA1E8F6E2C1_DELIVERED ON messenger_messages (queue_name, delivered_at);

-- ===========================================================================
-- PART 2 — FOREIGN KEY CONSTRAINTS
-- ===========================================================================

-- media_object (owner + linked entities)
ALTER TABLE media_object ADD CONSTRAINT FK_14D43132A2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE media_object ADD CONSTRAINT FK_14D43132463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre_de_sante (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE media_object ADD CONSTRAINT FK_14D43132BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE media_object ADD CONSTRAINT FK_14D43132B4B1C397 FOREIGN KEY (maladie_id) REFERENCES maladie (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;

-- user (identity verification documents)
ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6491B21CC5E FOREIGN KEY (piece_identite_id) REFERENCES media_object (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649A26FACA5 FOREIGN KEY (piece_identite_verso_id) REFERENCES media_object (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64992F2B792 FOREIGN KEY (photo_verification_identite_id) REFERENCES media_object (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

-- maladie / premier_soin / consultation
ALTER TABLE maladie ADD CONSTRAINT FK_ADC4024BBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE premier_soin ADD CONSTRAINT FK_AD8436B2B4B1C397 FOREIGN KEY (maladie_id) REFERENCES maladie (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE consultation ADD CONSTRAINT FK_964685A66B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE consultation ADD CONSTRAINT FK_964685A64F31A84 FOREIGN KEY (medecin_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

-- conversation ↔ message (circular dependency, resolved in this section)
ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E95928F487 FOREIGN KEY (dernier_message_id) REFERENCES message (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE message ADD CONSTRAINT FK_B6BD307F10335F61 FOREIGN KEY (expediteur_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE message ADD CONSTRAINT FK_B6BD307F62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE message ADD CONSTRAINT FK_B6BD307FEA9FDD75 FOREIGN KEY (media_id) REFERENCES media_object (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE message ADD CONSTRAINT FK_B6BD307F18C3CC46 FOREIGN KEY (message_parent_id) REFERENCES message (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED39AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

-- avis / prescription
ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF06B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF04F31A84 FOREIGN KEY (medecin_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D962FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D94F31A84 FOREIGN KEY (medecin_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D96B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D939626D86 FOREIGN KEY (superseded_by_id) REFERENCES prescription (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prescription_item ADD CONSTRAINT FK_1D4599EB93DB413D FOREIGN KEY (prescription_id) REFERENCES prescription (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

-- diagnostic engine
ALTER TABLE maladie_symptome ADD CONSTRAINT FK_941A7D2DB4B1C397 FOREIGN KEY (maladie_id) REFERENCES maladie (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE maladie_symptome ADD CONSTRAINT FK_941A7D2D12B83D77 FOREIGN KEY (symptome_id) REFERENCES symptome (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

-- notifications / refresh tokens / protocols / signalements
ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F2195E9276D FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE protocole_etape ADD CONSTRAINT FK_PROTOCOLE_ETAPE_PROTOCOLE FOREIGN KEY (protocole_id) REFERENCES protocole_premiers_gestes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE signalement_medecin ADD CONSTRAINT FK_SIGNALEMENT_PATIENT FOREIGN KEY (patient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE signalement_medecin ADD CONSTRAINT FK_SIGNALEMENT_MEDECIN FOREIGN KEY (medecin_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

-- ===========================================================================
-- PART 3 — MODULE CARTE SANTÉ (avis établissement, suggestions, affiliations,
--          demandes SOS, équipes / niveaux d'accès par établissement)
-- ===========================================================================

-- avis_etablissement
CREATE TABLE avis_etablissement (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    etablissement_id INT NOT NULL,
    user_id UUID DEFAULT NULL,
    note SMALLINT NOT NULL,
    commentaire TEXT DEFAULT NULL,
    statut VARCHAR(20) DEFAULT 'PUBLIE' NOT NULL,
    signale BOOLEAN DEFAULT false NOT NULL,
    raison_signalement TEXT DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
);
CREATE INDEX IDX_AVIS_ETAB_ETABLISSEMENT ON avis_etablissement (etablissement_id);
CREATE INDEX IDX_AVIS_ETAB_ETABLISSEMENT_STATUT ON avis_etablissement (etablissement_id, statut);

-- suggestion_etablissement
CREATE TABLE suggestion_etablissement (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    etablissement_id INT NOT NULL,
    user_id UUID DEFAULT NULL,
    champ VARCHAR(100) NOT NULL,
    valeur_proposee TEXT NOT NULL,
    commentaire TEXT DEFAULT NULL,
    statut VARCHAR(20) DEFAULT 'EN_ATTENTE' NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
);
CREATE INDEX IDX_SUGG_ETAB_ETABLISSEMENT ON suggestion_etablissement (etablissement_id);
CREATE INDEX IDX_SUGG_ETAB_STATUT ON suggestion_etablissement (statut);

-- affiliation_medecin
CREATE TABLE affiliation_medecin (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    medecin_id UUID NOT NULL,
    etablissement_id INT NOT NULL,
    fonction VARCHAR(255) DEFAULT NULL,
    salle VARCHAR(120) DEFAULT NULL,
    planning JSON DEFAULT NULL,
    teleconsultation BOOLEAN DEFAULT false NOT NULL,
    statut VARCHAR(20) DEFAULT 'EN_ATTENTE' NOT NULL,
    created_by_id UUID DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
);
CREATE INDEX IDX_AFF_MEDECIN_MEDECIN ON affiliation_medecin (medecin_id);
CREATE INDEX IDX_AFF_MEDECIN_ETABLISSEMENT ON affiliation_medecin (etablissement_id);
CREATE INDEX IDX_AFF_MEDECIN_STATUT ON affiliation_medecin (statut, etablissement_id);

-- demande_sos
CREATE TABLE demande_sos (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id UUID DEFAULT NULL,
    nom VARCHAR(255) DEFAULT NULL,
    telephone VARCHAR(255) DEFAULT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    description TEXT DEFAULT NULL,
    statut VARCHAR(20) DEFAULT 'EN_COURS' NOT NULL,
    proches JSON DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);
CREATE INDEX IDX_SOS_USER ON demande_sos (user_id);
CREATE INDEX IDX_SOS_STATUT_CREATED ON demande_sos (statut, created_at);

-- etablissement_equipe
CREATE TABLE etablissement_equipe (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    etablissement_id INT NOT NULL,
    user_id UUID NOT NULL,
    role VARCHAR(30) NOT NULL,
    statut VARCHAR(20) DEFAULT 'INVITE' NOT NULL,
    invite_par_id UUID DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
);
CREATE INDEX IDX_EQUIPE_ETABLISSEMENT ON etablissement_equipe (etablissement_id);
CREATE INDEX IDX_EQUIPE_USER ON etablissement_equipe (user_id);
CREATE INDEX IDX_EQUIPE_ACTIF_ROLE ON etablissement_equipe (etablissement_id, statut, role);

-- Contraintes de clés étrangères du module Carte Santé
ALTER TABLE avis_etablissement ADD CONSTRAINT FK_AVIS_ETABLISSEMENT FOREIGN KEY (etablissement_id) REFERENCES centre_de_sante (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE avis_etablissement ADD CONSTRAINT FK_AVIS_ETAB_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE suggestion_etablissement ADD CONSTRAINT FK_SUGG_ETABLISSEMENT FOREIGN KEY (etablissement_id) REFERENCES centre_de_sante (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE suggestion_etablissement ADD CONSTRAINT FK_SUGG_ETAB_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE affiliation_medecin ADD CONSTRAINT FK_AFF_MEDECIN FOREIGN KEY (medecin_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE affiliation_medecin ADD CONSTRAINT FK_AFF_ETABLISSEMENT FOREIGN KEY (etablissement_id) REFERENCES centre_de_sante (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE affiliation_medecin ADD CONSTRAINT FK_AFF_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE demande_sos ADD CONSTRAINT FK_SOS_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE etablissement_equipe ADD CONSTRAINT FK_EQUIPE_ETABLISSEMENT FOREIGN KEY (etablissement_id) REFERENCES centre_de_sante (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE etablissement_equipe ADD CONSTRAINT FK_EQUIPE_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE etablissement_equipe ADD CONSTRAINT FK_EQUIPE_INVITE_PAR FOREIGN KEY (invite_par_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;