export type HealthCatalogKind = 'service' | 'speciality'

export type HealthCatalogItem = {
  id: string
  kind: HealthCatalogKind
  fr: string
  en: string
}

/**
 * Curated baseline catalogue for Cameroon facilities. Values saved on a fiche
 * remain plain strings, so managers can always add a local/custom label.
 */
export const HEALTH_CATALOG: HealthCatalogItem[] = [
  ...[
    ['general-medicine', 'Médecine générale', 'General medicine'],
    ['internal-medicine', 'Médecine interne', 'Internal medicine'],
    ['cardiology', 'Cardiologie', 'Cardiology'],
    ['cardiovascular-surgery', 'Chirurgie cardiovasculaire', 'Cardiovascular surgery'],
    ['general-surgery', 'Chirurgie générale', 'General surgery'],
    ['digestive-surgery', 'Chirurgie digestive', 'Digestive surgery'],
    ['orthopedic-surgery', 'Chirurgie orthopédique', 'Orthopedic surgery'],
    ['traumatology', 'Traumatologie', 'Traumatology'],
    ['pediatric-surgery', 'Chirurgie pédiatrique', 'Pediatric surgery'],
    ['urologic-surgery', 'Chirurgie urologique', 'Urologic surgery'],
    ['plastic-surgery', 'Chirurgie plastique', 'Plastic surgery'],
    ['maxillofacial-surgery', 'Chirurgie maxillo-faciale', 'Maxillofacial surgery'],
    ['thoracic-surgery', 'Chirurgie thoracique', 'Thoracic surgery'],
    ['neurosurgery', 'Neurochirurgie', 'Neurosurgery'],
    ['pediatrics', 'Pédiatrie', 'Pediatrics'],
    ['neonatology', 'Néonatologie', 'Neonatology'],
    ['gynecology', 'Gynécologie', 'Gynecology'],
    ['obstetrics', 'Obstétrique', 'Obstetrics'],
    ['fertility', 'Fertilité et procréation', 'Fertility and reproduction'],
    ['oncology', 'Oncologie', 'Oncology'],
    ['hematology', 'Hématologie', 'Hematology'],
    ['nephrology', 'Néphrologie', 'Nephrology'],
    ['urology', 'Urologie', 'Urology'],
    ['gastroenterology', 'Gastro-entérologie', 'Gastroenterology'],
    ['hepatology', 'Hépatologie', 'Hepatology'],
    ['pneumology', 'Pneumologie', 'Pulmonology'],
    ['endocrinology', 'Endocrinologie', 'Endocrinology'],
    ['diabetology', 'Diabétologie', 'Diabetology'],
    ['rheumatology', 'Rhumatologie', 'Rheumatology'],
    ['dermatology', 'Dermatologie', 'Dermatology'],
    ['ophthalmology', 'Ophtalmologie', 'Ophthalmology'],
    ['ent', 'Oto-rhino-laryngologie', 'Otolaryngology'],
    ['odontology', 'Odontologie et soins dentaires', 'Odontology and dental care'],
    ['psychiatry', 'Psychiatrie', 'Psychiatry'],
    ['psychology', 'Psychologie clinique', 'Clinical psychology'],
    ['infectious-diseases', 'Maladies infectieuses', 'Infectious diseases'],
    ['tropical-medicine', 'Médecine tropicale', 'Tropical medicine'],
    ['emergency-medicine', "Médecine d'urgence", 'Emergency medicine'],
    ['anesthesia', 'Anesthésie-réanimation', 'Anesthesiology and intensive care'],
    ['radiology', 'Radiologie', 'Radiology'],
    ['nuclear-medicine', 'Médecine nucléaire', 'Nuclear medicine'],
    ['pathology', 'Anatomopathologie', 'Anatomic pathology'],
    ['medical-biology', 'Biologie médicale', 'Medical biology'],
    ['physical-rehabilitation', 'Médecine physique et réadaptation', 'Physical medicine and rehabilitation'],
    ['physiotherapy', 'Kinésithérapie', 'Physiotherapy'],
    ['nutrition', 'Nutrition et diététique', 'Nutrition and dietetics'],
    ['geriatrics', 'Gériatrie', 'Geriatrics'],
    ['occupational-medicine', 'Médecine du travail', 'Occupational medicine'],
    ['forensic-medicine', 'Médecine légale', 'Forensic medicine'],
    ['allergology', 'Allergologie', 'Allergology'],
    ['immunology', 'Immunologie', 'Immunology'],
    ['medical-genetics', 'Génétique médicale', 'Medical genetics'],
    ['vascular-medicine', 'Médecine vasculaire', 'Vascular medicine'],
    ['angiology', 'Angiologie', 'Angiology'],
    ['public-health', 'Santé publique', 'Public health'],
    ['community-medicine', 'Médecine communautaire', 'Community medicine'],
    ['family-medicine', 'Médecine familiale', 'Family medicine'],
    ['sports-medicine', 'Médecine du sport', 'Sports medicine'],
    ['sexology', 'Sexologie', 'Sexology'],
    ['addictology', 'Addictologie', 'Addiction medicine'],
    ['pain-medicine', 'Médecine de la douleur', 'Pain medicine'],
    ['palliative-care', 'Soins palliatifs', 'Palliative medicine'],
    ['sleep-medicine', 'Médecine du sommeil', 'Sleep medicine'],
    ['geriatric-psychiatry', 'Psychiatrie gériatrique', 'Geriatric psychiatry'],
    ['speech-therapy', 'Orthophonie', 'Speech therapy'],
    ['occupational-therapy', 'Ergothérapie', 'Occupational therapy'],
  ].map(([id, fr, en]) => ({ id, kind: 'speciality' as const, fr, en })),
  ...[
    ['emergency-department', 'Urgences', 'Emergency department'],
    ['outpatient-consultations', 'Consultations externes', 'Outpatient consultations'],
    ['inpatient-care', 'Hospitalisation', 'Inpatient care'],
    ['maternity', 'Maternité', 'Maternity'],
    ['operating-room', 'Bloc opératoire', 'Operating room'],
    ['intensive-care', 'Réanimation', 'Intensive care'],
    ['neonatal-intensive-care', 'Réanimation néonatale', 'Neonatal intensive care'],
    ['critical-care', 'Soins intensifs', 'Critical care'],
    ['laboratory', 'Laboratoire', 'Laboratory'],
    ['medical-imaging', 'Imagerie médicale', 'Medical imaging'],
    ['x-ray', 'Radiographie', 'X-ray'],
    ['ultrasound', 'Échographie', 'Ultrasound'],
    ['ct-scan', 'Scanner / tomodensitométrie', 'CT scan'],
    ['mri', 'IRM', 'MRI'],
    ['mammography', 'Mammographie', 'Mammography'],
    ['pharmacy', 'Pharmacie', 'Pharmacy'],
    ['blood-bank', 'Banque de sang', 'Blood bank'],
    ['dialysis', 'Hémodialyse', 'Hemodialysis'],
    ['chemotherapy', 'Chimiothérapie', 'Chemotherapy'],
    ['radiotherapy', 'Radiothérapie', 'Radiotherapy'],
    ['endoscopy', 'Endoscopie', 'Endoscopy'],
    ['colonoscopy', 'Coloscopie', 'Colonoscopy'],
    ['vaccination', 'Vaccination', 'Vaccination'],
    ['screening', 'Dépistage', 'Screening'],
    ['family-planning', 'Planning familial', 'Family planning'],
    ['maternal-health', 'Santé maternelle', 'Maternal health'],
    ['child-health', 'Santé infantile', 'Child health'],
    ['prenatal-care', 'Consultation prénatale', 'Prenatal care'],
    ['postnatal-care', 'Suivi postnatal', 'Postnatal care'],
    ['delivery', 'Accouchement', 'Delivery'],
    ['cesarean-section', 'Césarienne', 'Caesarean section'],
    ['ivf', 'Procréation médicalement assistée', 'Assisted reproduction'],
    ['minor-surgery', 'Chirurgie ambulatoire', 'Day surgery'],
    ['wound-care', 'Soins des plaies', 'Wound care'],
    ['burns-care', 'Prise en charge des brûlures', 'Burns care'],
    ['infectious-disease-clinic', 'Clinique des maladies infectieuses', 'Infectious disease clinic'],
    ['hiv-care', 'Prise en charge VIH', 'HIV care'],
    ['tuberculosis-care', 'Prise en charge tuberculose', 'Tuberculosis care'],
    ['malaria-care', 'Prise en charge du paludisme', 'Malaria care'],
    ['diabetes-clinic', 'Clinique du diabète', 'Diabetes clinic'],
    ['hypertension-clinic', 'Clinique de l’hypertension', 'Hypertension clinic'],
    ['cardiac-rehabilitation', 'Réadaptation cardiaque', 'Cardiac rehabilitation'],
    ['physiotherapy-unit', 'Unité de kinésithérapie', 'Physiotherapy unit'],
    ['mental-health', 'Santé mentale', 'Mental health services'],
    ['psychological-support', 'Soutien psychologique', 'Psychological support'],
    ['social-work', 'Service social', 'Social work'],
    ['nutrition-counselling', 'Conseil nutritionnel', 'Nutrition counselling'],
    ['pain-clinic', 'Clinique de la douleur', 'Pain clinic'],
    ['palliative-care-unit', 'Unité de soins palliatifs', 'Palliative care unit'],
    ['home-care', 'Soins à domicile', 'Home care'],
    ['teleconsultation', 'Téléconsultation', 'Teleconsultation'],
    ['ambulance', 'Service d’ambulance', 'Ambulance service'],
    ['patient-transport', 'Transport sanitaire', 'Patient transport'],
    ['medical-certificates', 'Certificats médicaux', 'Medical certificates'],
    ['occupational-health', 'Médecine du travail', 'Occupational health service'],
    ['health-education', 'Éducation à la santé', 'Health education'],
    ['community-outreach', 'Sensibilisation communautaire', 'Community outreach'],
    ['home-sampling', 'Prélèvement à domicile', 'Home sample collection'],
    ['rapid-tests', 'Tests rapides', 'Rapid tests'],
    ['pathology-lab', 'Anatomopathologie de laboratoire', 'Pathology laboratory'],
    ['genetic-testing', 'Tests génétiques', 'Genetic testing'],
    ['eye-screening', 'Dépistage visuel', 'Eye screening'],
    ['dental-emergency', 'Urgences dentaires', 'Dental emergency'],
    ['oral-hygiene', 'Hygiène bucco-dentaire', 'Oral hygiene'],
    ['hearing-test', 'Bilan auditif', 'Hearing test'],
    ['speech-therapy-service', 'Service d’orthophonie', 'Speech therapy service'],
    ['rehabilitation', 'Réadaptation fonctionnelle', 'Functional rehabilitation'],
    ['prosthetics', 'Appareillage et prothèses', 'Prosthetics and orthotics'],
    ['medical-device-rental', 'Location de matériel médical', 'Medical equipment rental'],
    ['follow-up', 'Suivi médical', 'Medical follow-up'],
    ['second-opinion', 'Deuxième avis médical', 'Second medical opinion'],
  ].map(([id, fr, en]) => ({ id, kind: 'service' as const, fr, en })),
]

export const SPECIALITY_CATALOG = HEALTH_CATALOG.filter((item) => item.kind === 'speciality')
export const SERVICE_CATALOG = HEALTH_CATALOG.filter((item) => item.kind === 'service')
