#!/usr/bin/env python3
"""
generate_seed_sql.py — MediSecours+ seed generator.

Reads the reference disease / health centre catalogs and emits a single
standalone PostgreSQL seed file (database/seed.sql) that runs on any fresh
database created from database/schema.sql.

Sources:
  - medisecours-backend/data/maladies.json       (1038 diseases, UTF-8)
  - medisecours-backend/data/centres_sante.json  (232 health centres, UTF-8)

What the seed DOES cover:  categorie, maladie, premier_soin, centre_de_sante.

What the seed deliberately does NOT cover (generated by the backend itself):
  - symptome / maladie_symptome   -> BuildSymptomIndexCommand (bootstrap)
  - protocole_premiers_gestes / etapes -> GenerateFirstAidCatalogCommand
  - patient_visible flags        -> BuildPatientDiseaseCatalogCommand
  - reference_data_version rows  -> written by the commands above
  - user accounts                -> created via app:create-admin at deploy

Run:
  python tools/generate_seed_sql.py
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MALADIES = os.path.join(ROOT, "medisecours-backend", "data", "maladies.json")
CENTRES = os.path.join(ROOT, "medisecours-backend", "data", "centres_sante.json")
OUT = os.path.join(ROOT, "database", "seed.sql")


def esc(value):
    """Escape a value for a Postgres single-quoted string literal."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    s = str(value).replace("'", "''")
    return f"'{s}'"


def js(arr):
    """Serialize a JSON value for a JSON/TEXT column (single-quoted literal)."""
    if not arr:
        return "'[]'"
    return esc(json.dumps(arr, ensure_ascii=False))


def main():
    with open(MALADIES, "r", encoding="utf-8") as f:
        maladies = json.load(f)
    with open(CENTRES, "r", encoding="utf-8") as f:
        centres = json.load(f)

    if not isinstance(maladies, list) or not isinstance(centres, list):
        sys.exit("Unexpected JSON shape (expected a top-level array).")

    # Collect the distinct categories referenced by diseases.
    categories = {}
    for m in maladies:
        name = (m.get("categorie") or "Non classifie").strip()
        if name and name not in categories:
            categories[name] = True

    out = []
    out.append("-- ============================================================================")
    out.append("-- MediSecours+ seed data — generated by tools/generate_seed_sql.py")
    out.append(f"--   {len(maladies)} maladies, {len(categories)} categories, {len(centres)} centres")
    out.append("-- ============================================================================")
    out.append("")
    out.append("-- Safety guard: refuse to re-seed an already-initialised database.")
    out.append("DO $$")
    out.append("BEGIN")
    out.append("    IF NOT EXISTS (SELECT 1 FROM information_schema.tables")
    out.append("                   WHERE table_schema = 'public' AND table_name = 'reference_data_version') THEN")
    out.append("        RAISE NOTICE 'Schema not found — run database/schema.sql first.';")
    out.append("    ELSIF EXISTS (SELECT 1 FROM reference_data_version WHERE dataset = 'maladies') THEN")
    out.append("        RAISE EXCEPTION 'Seed already applied (reference_data_version.maladies is set).'")
    out.append("                      ' Delete that row first if you really want to re-seed.';")
    out.append("    END IF;")
    out.append("END $$;")
    out.append("")
    out.append("BEGIN;")
    out.append("")
    out.append("-- Catastrophic-safe reset: only meaningful on a FRESH database created from schema.sql.")
    out.append("-- CASCADE also empties dependent tables (maladie_symptome, media_object, ...).")
    out.append("TRUNCATE TABLE centre_de_sante, premier_soin, maladie, categorie RESTART IDENTITY CASCADE;")
    out.append("")

    # ---- categories -------------------------------------------------------
    out.append("-- Categories")
    out.append("INSERT INTO categorie (nom, description, couleur, icone, created_at, updated_at) VALUES")
    cat_rows = []
    for i, name in enumerate(categories.keys()):
        separator = "" if i == len(categories) - 1 else ","
        cat_rows.append(
            f"({esc(name)}, NULL, NULL, NULL, NOW(), NOW()){separator}"
        )
    out.append("\n".join(cat_rows))
    out.append(";")
    out.append("")

    # ---- maladies ---------------------------------------------------------
    out.append("-- Maladies")
    out.append("INSERT INTO maladie (")
    out.append("    nom, description, symptomes, precautions, traitement, causes,")
    out.append("    niveau_gravite, contagieux, urgence, is_accident, type_accident, image_url,")
    out.append("    created_at, updated_at, categorie_id)")
    out.append("VALUES")
    mal_rows = []
    for i, m in enumerate(maladies):
        nom = m.get("nom") or "Maladie non renseignee"
        cat_name = (m.get("categorie") or "Non classifie").strip()
        separator = "" if i == len(maladies) - 1 else ","
        mal_rows.append(
            "("
            f"{esc(nom)}, "
            f"{esc(m.get('description'))}, "
            f"{esc(m.get('symptomes'))}, "
            f"{esc(m.get('precautions'))}, "
            f"{esc(m.get('traitement'))}, "
            f"{esc(m.get('causes'))}, "
            f"{esc((m.get('niveauGravite') or 'INCONNU').upper())}, "
            f"{esc(m.get('contagieux'))}, "
            f"{esc(m.get('urgence'))}, "
            f"{esc(m.get('isAccident'))}, "
            f"{esc(m.get('typeAccident'))}, "
            f"{esc(m.get('imageUrl'))}, "
            "NOW(), NOW(), "
            f"(SELECT id FROM categorie WHERE nom = {esc(cat_name)} LIMIT 1)"
            f"){separator}"
        )
    out.append("\n".join(mal_rows))
    out.append(";")
    out.append("")

    # ---- premier soin -----------------------------------------------------
    ps_payload = []
    for m in maladies:
        maladie_name = m.get("nom") or "Maladie non renseignee"
        for ps in m.get("premiersSoins") or []:
            ps_payload.append(
                "("
                f"{esc(ps.get('titre'))}, "
                f"{esc(ps.get('description'))}, "
                f"{esc(ps.get('symptomes'))}, "
                f"{esc((ps.get('niveauUrgence') or 'MOYEN').upper())}, "
                f"(SELECT id FROM maladie WHERE nom = {esc(maladie_name)} ORDER BY id LIMIT 1)"
                "),"
            )
    if ps_payload:
        out.append("-- Premiers soins")
        out.append("INSERT INTO premier_soin (titre, description, symptomes, niveau_urgence, maladie_id) VALUES")
        out.append("\n".join(ps_payload)[:-1] + ";")
        out.append("")

    # ---- centres ----------------------------------------------------------
    out.append("-- Centres de sante")
    out.append("INSERT INTO centre_de_sante (")
    out.append("    nom, adresse, latitude, longitude, telephone, horaires, type, ville, region,")
    out.append("    specialites, services, description, est_actif, urgences24h, email, site_web,")
    out.append("    statut, quartier, image_url)")
    out.append("VALUES")
    centre_rows = []
    for i, c in enumerate(centres):
        separator = "" if i == len(centres) - 1 else ","
        statut = (c.get("statut") or "prive").lower()
        if statut not in ("public", "prive"):
            statut = "prive"
        centre_rows.append(
            "("
            f"{esc(c.get('nom'))}, "
            f"{esc(c.get('adresse'))}, "
            f"{float(c.get('latitude') or 0)}, "
            f"{float(c.get('longitude') or 0)}, "
            f"{esc(c.get('telephone'))}, "
            f"{esc(c.get('horaires'))}, "
            f"{esc(c.get('type'))}, "
            f"{esc(c.get('ville'))}, "
            f"{esc(c.get('region'))}, "
            f"{js(c.get('specialites'))}, "
            f"{js(c.get('services'))}, "
            f"{esc(c.get('description'))}, "
            f"{esc(c.get('estActif'))}, "
            f"{esc(c.get('urgences24h'))}, "
            f"{esc(c.get('email'))}, "
            f"{esc(c.get('siteWeb'))}, "
            f"{esc(statut)}, "
            f"{esc(c.get('quartier'))}, "
            f"{esc(c.get('imageUrl'))}"
            f"){separator}"
        )
    out.append("\n".join(centre_rows))
    out.append(";")
    out.append("")
    out.append("COMMIT;")
    out.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))

    print(f"OK — wrote {OUT}")
    print(f"  categories : {len(categories)}")
    print(f"  maladies   : {len(maladies)}")
    print(f"  premiers   : {len(ps_payload)}")
    print(f"  centres    : {len(centres)}")


if __name__ == "__main__":
    main()