<?php

declare(strict_types=1);

namespace App\Service;

/** Gestes principaux utilises dans les protocoles maitres. */
final class FirstAidActionLibrary
{
    /** @var array<string, array{titre: string, instruction: string}> */
    public const ACTIONS = [
        'difficulte_respiratoire' => ['titre' => 'Installer dans la position où la respiration est la plus facile', 'instruction' => 'Laisser la personne assise ou demi-assise, desserrer les vêtements serrés et la maintenir au calme. L’aider uniquement à utiliser son propre traitement de secours déjà prescrit si elle le demande et peut l’utiliser elle-même.'],
        'etouffement' => ['titre' => 'Adapter le geste à l’efficacité de la toux', 'instruction' => 'Si la personne parle et tousse efficacement, l’encourager à tousser. Si elle ne peut plus parler, respirer ou tousser efficacement, donner jusqu’à cinq claques fermes entre les omoplates puis appliquer les manœuvres de désobstruction adaptées à son âge, en alternance, jusqu’à expulsion ou perte de connaissance.'],
        'arret_cardiorespiratoire' => ['titre' => 'Commencer immédiatement la réanimation', 'instruction' => 'Appeler les secours, commencer les compressions thoraciques et utiliser un défibrillateur automatisé externe dès qu’il est disponible. Suivre la séquence détaillée de réanimation affichée dans cette fiche.'],
        'noyade' => ['titre' => 'Sortir de l’eau uniquement sans vous exposer', 'instruction' => 'Utiliser un objet flottant ou demander l’aide de sauveteurs. Une fois la personne hors de l’eau, vérifier sa respiration. Si elle ne respire pas normalement, commencer la réanimation ; réaliser des insufflations si vous êtes formé et suivre immédiatement les consignes des secours.'],
        'inhalation_fumee' => ['titre' => 'Amener à l’air libre sans entrer dans la zone enfumée', 'instruction' => 'Éloigner la personne de la fumée uniquement si cela peut être fait sans danger. La laisser au repos, surveiller la respiration et appeler les secours même si les symptômes paraissent s’améliorer après une exposition importante.'],
        'crise_asthme' => ['titre' => 'Aider à utiliser le traitement de secours prescrit', 'instruction' => 'Installer la personne assise, la rassurer et l’aider à prendre son inhalateur de secours personnel selon son plan habituel. Appeler rapidement si elle parle difficilement, s’épuise, bleuit ou ne s’améliore pas.'],
        'hyperventilation' => ['titre' => 'Ralentir l’environnement et accompagner la respiration', 'instruction' => 'Installer la personne au calme, parler lentement et l’encourager à respirer doucement sans forcer. Rechercher une douleur thoracique, un malaise ou une difficulté respiratoire réelle et demander un avis médical si le doute persiste.'],
        'cyanose' => ['titre' => 'Traiter comme une urgence respiratoire', 'instruction' => 'Installer la personne dans la position où elle respire le mieux, limiter tout effort et appeler immédiatement les secours. Vérifier continuellement la réponse et la respiration.'],
        'obstruction_nourrisson' => ['titre' => 'Désobstruer avec les gestes adaptés au nourrisson', 'instruction' => 'Si le nourrisson ne peut plus tousser ou respirer efficacement, alterner jusqu’à cinq claques dans le dos et cinq compressions thoraciques. Ne pas pratiquer de compression abdominale. S’il devient inconscient, commencer la réanimation adaptée au nourrisson.'],
        'detresse_respiratoire_enfant' => ['titre' => 'Maintenir l’enfant dans sa position de confort', 'instruction' => 'Garder l’enfant calme, assis ou dans les bras de son accompagnant, dans la position où il respire le mieux. Ne pas le forcer à s’allonger, boire ou manger et appeler immédiatement en présence d’épuisement, de creusement des côtes ou de coloration bleue.'],

        'perte_de_connaissance' => ['titre' => 'Maintenir les voies aériennes ouvertes', 'instruction' => 'Si la personne respire normalement, la placer sur le côté en position latérale de sécurité et surveiller sa respiration. Si elle ne respire pas normalement, commencer immédiatement la réanimation et utiliser un DAE dès que possible.'],
        'convulsion' => ['titre' => 'Protéger pendant la crise', 'instruction' => 'Éloigner les objets dangereux, protéger la tête avec un support souple et noter l’heure de début. Après les secousses, vérifier la respiration et placer sur le côté si elle est normale.'],
        'malaise' => ['titre' => 'Installer au repos et rechercher une aggravation', 'instruction' => 'Aider la personne à s’asseoir ou s’allonger selon son confort, rester auprès d’elle et recueillir l’heure de début, les symptômes et les antécédents utiles. Appeler si le malaise persiste, récidive ou s’accompagne d’un signe de danger.'],
        'avc_suspecte' => ['titre' => 'Noter l’heure et appeler immédiatement', 'instruction' => 'Demander à la personne de sourire, lever les deux bras et répéter une phrase simple. En cas d’asymétrie du visage, faiblesse d’un bras ou trouble de parole, noter l’heure de début et appeler immédiatement les secours.'],
        'hypoglycemie_consciente' => ['titre' => 'Donner du sucre seulement si la déglutition est sûre', 'instruction' => 'Si la personne est pleinement consciente et peut avaler sans risque, lui donner une source de sucre rapide disponible puis surveiller l’amélioration. Si elle ne s’améliore pas rapidement, s’aggrave ou ne peut plus avaler, appeler les secours.'],
        'hypoglycemie_inconsciente' => ['titre' => 'Protéger les voies aériennes sans rien donner par la bouche', 'instruction' => 'Ne rien faire boire ou manger. Vérifier la respiration, placer sur le côté si elle respire normalement et utiliser uniquement un dispositif de secours personnel prescrit si une personne formée sait l’administrer.'],
        'hyperglycemie_grave' => ['titre' => 'Mettre au repos et organiser une évaluation urgente', 'instruction' => 'Laisser la personne au repos, consciente, et lui permettre de boire de petites quantités d’eau seulement si elle avale normalement et ne vomit pas. Ne pas administrer ni modifier une dose d’insuline à sa place.'],
        'confusion_aigue' => ['titre' => 'Rester auprès de la personne et sécuriser ses déplacements', 'instruction' => 'Installer la personne dans un endroit calme, empêcher une chute ou une errance dangereuse et rechercher une faiblesse d’un côté, une difficulté à parler, une fièvre ou un traumatisme.'],
        'syncope_chaleur' => ['titre' => 'Allonger au frais et refroidir progressivement', 'instruction' => 'Déplacer la personne vers un lieu frais, l’allonger et desserrer ses vêtements. Vérifier la respiration et refroidir doucement avec de l’eau et de l’air en attendant l’évaluation.'],
        'crise_panique' => ['titre' => 'Réduire les stimulations et accompagner calmement', 'instruction' => 'Rester avec la personne, l’éloigner du bruit et parler avec des phrases courtes. Encourager une respiration lente sans utiliser de sac en papier et vérifier qu’aucun signe physique grave n’explique les symptômes.'],

        'douleur_thoracique' => ['titre' => 'Arrêter tout effort et appeler les secours', 'instruction' => 'Installer la personne au repos dans une position confortable, desserrer les vêtements et appeler immédiatement. Ne lui donner que son propre médicament d’urgence déjà prescrit si elle le demande et peut le prendre elle-même.'],
        'choc_circulatoire' => ['titre' => 'Allonger et préserver la température corporelle', 'instruction' => 'Allonger la personne si sa respiration le permet, contrôler tout saignement visible et la couvrir légèrement. Ne rien donner par la bouche et surveiller continuellement respiration et conscience.'],

        'saignement_externe_important' => ['titre' => 'Comprimer directement la plaie', 'instruction' => 'Avec des gants ou une protection si disponible, appuyer fermement et sans interruption sur la plaie avec une compresse ou un tissu propre. Ajouter du matériel par-dessus s’il est imbibé sans retirer la première couche.'],
        'plaie' => ['titre' => 'Nettoyer et protéger la plaie', 'instruction' => 'Se laver les mains, rincer la plaie simple avec de l’eau propre, retirer uniquement les saletés superficielles faciles à enlever puis couvrir avec un pansement propre.'],
        'saignement_nez' => ['titre' => 'Comprimer les narines en penchant la tête vers l’avant', 'instruction' => 'Faire asseoir la personne, tête légèrement penchée vers l’avant, puis pincer la partie souple du nez sans relâcher pendant dix à quinze minutes. Lui demander de respirer par la bouche.'],
        'amputation' => ['titre' => 'Contrôler le saignement et conserver la partie amputée', 'instruction' => 'Comprimer la plaie et appeler immédiatement. Envelopper la partie amputée dans une compresse propre légèrement humide, la placer dans un sac fermé puis garder ce sac au frais sans contact direct avec la glace.'],
        'objet_plante' => ['titre' => 'Stabiliser l’objet sans le retirer', 'instruction' => 'Maintenir l’objet immobile en plaçant des compresses ou tissus propres autour, sans appuyer dessus. Contrôler le saignement autour de la plaie et organiser un transfert urgent.'],
        'plaie_oculaire' => ['titre' => 'Protéger l’œil sans exercer de pression', 'instruction' => 'Empêcher la personne de frotter l’œil. Couvrir très légèrement sans appuyer ni retirer un objet planté et limiter les mouvements des yeux pendant le transfert urgent.'],
        'dent_expulsee' => ['titre' => 'Conserver la dent humide et consulter immédiatement', 'instruction' => 'Tenir la dent définitive par la couronne sans toucher la racine. Si elle est sale, la rincer brièvement sans frotter puis la conserver dans du lait ou une solution adaptée et rejoindre rapidement un dentiste.'],
        'morsure_humaine' => ['titre' => 'Laver abondamment et couvrir', 'instruction' => 'Rincer la morsure avec de l’eau propre et du savon, contrôler le saignement puis couvrir avec un pansement propre. Une évaluation médicale rapide est nécessaire en raison du risque infectieux.'],
        'morsure_animale' => ['titre' => 'Laver immédiatement et organiser l’évaluation antirabique', 'instruction' => 'Laver la plaie abondamment avec de l’eau et du savon pendant plusieurs minutes, appliquer un antiseptique si disponible et couvrir légèrement. Consulter rapidement pour évaluer rage, tétanos et infection.'],
        'ecrasement_membre' => ['titre' => 'Ne pas libérer une victime lourdement coincée sans les secours', 'instruction' => 'Sécuriser la zone, appeler les secours et surveiller la respiration. Si le membre est déjà libéré, contrôler tout saignement, immobiliser et ne rien donner par la bouche.'],

        'brulure' => ['titre' => 'Refroidir sous l’eau courante tempérée', 'instruction' => 'Éloigner la source, retirer les vêtements ou bijoux non collés puis refroidir la brûlure avec de l’eau courante tempérée pendant vingt minutes. Couvrir ensuite sans serrer avec un matériau propre non adhérent.'],
        'brulure_chimique' => ['titre' => 'Retirer le produit et rincer abondamment', 'instruction' => 'Se protéger, retirer à sec les poudres visibles puis enlever les vêtements contaminés. Rincer immédiatement et longuement à l’eau propre en évitant de contaminer une autre zone.'],
        'brulure_electrique' => ['titre' => 'Couper le courant avant tout contact', 'instruction' => 'Ne toucher la personne qu’après coupure certaine de l’électricité. Vérifier réponse et respiration, commencer la réanimation si nécessaire puis couvrir les brûlures visibles sans appliquer de produit.'],
        'brulure_liquide_chaud' => ['titre' => 'Retirer les vêtements non collés et refroidir', 'instruction' => 'Éloigner le liquide chaud, retirer rapidement les vêtements et bijoux non collés, puis refroidir la zone sous l’eau courante tempérée pendant vingt minutes.'],
        'brulure_solaire' => ['titre' => 'Mettre à l’ombre et refroidir la peau', 'instruction' => 'Interrompre l’exposition, rafraîchir la peau avec de l’eau tempérée et faire boire régulièrement si la personne est consciente. Consulter en cas de cloques étendues, malaise, fièvre ou atteinte d’un jeune enfant.'],
        'brulure_visage' => ['titre' => 'Refroidir sans retarder l’appel', 'instruction' => 'Appeler immédiatement, éloigner de la source et refroidir doucement les zones accessibles avec de l’eau tempérée. Maintenir la personne assise si elle respire mieux ainsi et surveiller voix, toux et respiration.'],
        'brulure_oculaire_chimique' => ['titre' => 'Rincer l’œil immédiatement et continuellement', 'instruction' => 'Maintenir les paupières ouvertes et rincer avec beaucoup d’eau propre de l’intérieur vers l’extérieur pendant au moins vingt minutes. Retirer les lentilles si elles se détachent facilement.'],

        'intoxication' => ['titre' => 'Identifier le produit sans provoquer de vomissement', 'instruction' => 'Éloigner le produit sans vous contaminer, conserver l’emballage et noter quantité et heure possibles. Ne rien faire avaler et demander immédiatement une consigne professionnelle.'],
        'surdosage_medicament' => ['titre' => 'Conserver les emballages et appeler immédiatement', 'instruction' => 'Rassembler les boîtes, ordonnances et informations sur l’heure et la quantité supposée. Vérifier respiration et conscience, ne pas provoquer de vomissement et ne rien administrer pour neutraliser le produit.'],
        'intoxication_pesticide' => ['titre' => 'Se protéger et retirer les vêtements contaminés', 'instruction' => 'Éloigner de la zone sans vous exposer, aérer si cela est sûr, retirer les vêtements contaminés avec des gants et rincer la peau exposée à grande eau. Appeler immédiatement avec le nom du produit.'],
        'monoxyde_carbone' => ['titre' => 'Sortir à l’air libre sans entrer dans le local dangereux', 'instruction' => 'Ne pas pénétrer dans un espace suspect. Si cela est possible sans risque, faire sortir la personne à l’air libre, appeler les secours et surveiller la respiration jusqu’à leur arrivée.'],
        'intoxication_alcool' => ['titre' => 'Prévenir l’étouffement et l’hypothermie', 'instruction' => 'Rester avec la personne, la placer sur le côté si elle somnole mais respire normalement et la couvrir légèrement. Vérifier souvent la respiration et appeler si elle est difficile à réveiller, vomit répétitivement ou respire anormalement.'],
        'ingestion_hydrocarbure' => ['titre' => 'Ne pas faire vomir et appeler immédiatement', 'instruction' => 'Éloigner le produit, rincer doucement la bouche sans faire avaler d’eau et conserver l’emballage. Ne pas provoquer de vomissement en raison du risque d’inhalation dans les poumons.'],
        'intoxication_alimentaire' => ['titre' => 'Prévenir la déshydratation et conserver les informations utiles', 'instruction' => 'Faire boire une solution de réhydratation par petites gorgées si la personne est consciente et avale normalement. Noter les aliments consommés et consulter si les symptômes sont importants ou touchent une personne fragile.'],
        'champignon_toxique' => ['titre' => 'Conserver un échantillon et appeler sans attendre', 'instruction' => 'Conserver les restes du repas, photos ou échantillons sans les manipuler inutilement. Ne pas provoquer de vomissement, ne rien donner comme antidote domestique et contacter immédiatement un professionnel.'],
        'projection_produit_peau' => ['titre' => 'Retirer les vêtements contaminés et rincer', 'instruction' => 'Se protéger, enlever les vêtements et bijoux contaminés puis rincer abondamment la peau à l’eau courante. Ne pas frotter et ne pas appliquer de produit neutralisant.'],
        'inhalation_produit_chimique' => ['titre' => 'Quitter la zone contaminée sans vous exposer', 'instruction' => 'Ne pas entrer sans protection dans la zone. Amener la personne à l’air libre si cela est sûr, desserrer ses vêtements et appeler immédiatement avec le nom du produit.'],
        'morsure_serpent' => ['titre' => 'Immobiliser la personne et le membre atteint', 'instruction' => 'Éloigner du serpent sans tenter de le capturer, allonger et rassurer la personne, retirer bagues et bracelets puis immobiliser le membre. Organiser un transfert urgent en limitant la marche.'],
        'piqure_scorpion' => ['titre' => 'Nettoyer et surveiller les signes généraux', 'instruction' => 'Laver la zone, retirer les bijoux proches et maintenir le membre au repos. Appeler rapidement en cas de douleur intense, vomissements, agitation, salivation, difficulté respiratoire ou chez un enfant.'],
        'exposition_rage' => ['titre' => 'Laver immédiatement la zone exposée', 'instruction' => 'Laver et rincer abondamment la morsure, griffure ou muqueuse exposée avec de l’eau et du savon pendant environ quinze minutes, appliquer un antiseptique si disponible puis consulter en urgence pour la prophylaxie.'],

        'reaction_allergique' => ['titre' => 'Éloigner l’allergène et surveiller la respiration', 'instruction' => 'Arrêter l’exposition si possible, installer au repos et surveiller l’apparition d’un gonflement du visage ou de la langue, d’une voix modifiée, d’une gêne respiratoire ou d’un malaise.'],
        'anaphylaxie' => ['titre' => 'Utiliser l’auto-injecteur prescrit et appeler immédiatement', 'instruction' => 'Aider la personne à utiliser son auto-injecteur d’adrénaline personnel dans la face externe de la cuisse, selon son plan d’urgence. Appeler immédiatement et l’allonger, sauf si elle respire mieux assise.'],
        'piqure_insecte' => ['titre' => 'Retirer le dard visible et refroidir localement', 'instruction' => 'Retirer rapidement un dard visible en le raclant ou le saisissant sans retarder le geste, laver la zone et appliquer du froid enveloppé. Surveiller toute réaction générale.'],
        'allergie_alimentaire' => ['titre' => 'Arrêter l’ingestion et rechercher une anaphylaxie', 'instruction' => 'Retirer l’aliment, rincer la bouche si possible et surveiller immédiatement respiration, voix, gonflement, vomissements et malaise. Utiliser l’auto-injecteur personnel si les critères du plan d’urgence sont présents.'],

        'traumatisme' => ['titre' => 'Immobiliser dans la position trouvée', 'instruction' => 'Demander à la personne de ne pas bouger la zone douloureuse, soutenir le membre dans la position la plus confortable et appliquer du froid enveloppé uniquement sur une lésion fermée.'],
        'traumatisme_cranien' => ['titre' => 'Maintenir au repos et surveiller la conscience', 'instruction' => 'Limiter les mouvements de la tête et du cou, contrôler un saignement sans appuyer sur une déformation et surveiller vomissements, confusion, somnolence, convulsion ou faiblesse.'],
        'traumatisme_colonne' => ['titre' => 'Empêcher les mouvements inutiles', 'instruction' => 'Demander à la personne de rester immobile, maintenir manuellement la tête dans la position trouvée si cela est possible et surveiller la respiration. Ne la déplacer qu’en présence d’un danger immédiat.'],
        'fracture_suspectee' => ['titre' => 'Soutenir le membre sans le réaligner', 'instruction' => 'Immobiliser la zone dans la position trouvée avec des coussins ou supports, retirer délicatement les bijoux proches avant gonflement et appliquer du froid enveloppé sur une lésion fermée.'],
        'entorse' => ['titre' => 'Protéger, refroidir et surélever si possible', 'instruction' => 'Arrêter l’activité, soutenir l’articulation, appliquer du froid enveloppé par périodes courtes et surélever si cela reste confortable. Faire examiner en cas d’impossibilité d’appui ou de déformation.'],
        'luxation' => ['titre' => 'Immobiliser sans remettre en place', 'instruction' => 'Soutenir l’articulation exactement dans la position trouvée, appliquer du froid enveloppé autour sans pression et organiser une évaluation rapide.'],
        'traumatisme_thoracique' => ['titre' => 'Installer dans la position où la respiration est la plus facile', 'instruction' => 'Limiter les mouvements, laisser la personne assise ou demi-assise si elle le préfère et couvrir une plaie ouverte avec un pansement propre sans comprimer fortement le thorax.'],
        'traumatisme_abdominal' => ['titre' => 'Allonger au repos sans appuyer sur l’abdomen', 'instruction' => 'Installer confortablement, souvent genoux légèrement fléchis si cela soulage, couvrir et surveiller. Ne rien donner à boire ou à manger et ne pas repousser un organe extériorisé.'],
        'traumatisme_bassin' => ['titre' => 'Ne pas mobiliser et prévenir le choc', 'instruction' => 'Laisser la personne allongée dans la position trouvée, empêcher qu’elle se lève ou marche, la couvrir et surveiller respiration, pâleur et malaise jusqu’aux secours.'],
        'corps_etranger_oeil' => ['titre' => 'Rincer sans frotter', 'instruction' => 'Empêcher le frottement et rincer doucement avec de l’eau propre si le corps étranger est superficiel et non planté. Ne pas tenter de retirer un objet incrusté.'],
        'fracture_dentaire' => ['titre' => 'Rincer, protéger et conserver le fragment', 'instruction' => 'Rincer doucement la bouche, comprimer un saignement avec une compresse et conserver tout fragment de dent dans du lait ou une solution adaptée avant la consultation dentaire.'],
        'electrocution' => ['titre' => 'Couper la source électrique puis vérifier la respiration', 'instruction' => 'Ne pas toucher la personne tant que le courant n’est pas coupé. Après sécurisation, vérifier réponse et respiration, commencer la réanimation si nécessaire et couvrir les brûlures visibles.'],
        'accident_route' => ['titre' => 'Protéger la zone sans déplacer inutilement les victimes', 'instruction' => 'Signaler l’accident, couper le contact si cela est possible sans risque et appeler en indiquant nombre de victimes et dangers. Ne sortir une personne d’un véhicule qu’en cas de danger immédiat.'],
        'chute_hauteur' => ['titre' => 'Maintenir immobile et surveiller', 'instruction' => 'Ne pas relever la personne. Maintenir tête et cou dans la position trouvée, contrôler tout saignement important et surveiller continuellement respiration et conscience.'],
        'effondrement_ecrasement' => ['titre' => 'Attendre les équipes de sauvetage spécialisées', 'instruction' => 'Ne pas entrer dans une structure instable et ne pas déplacer des charges lourdes seul. Appeler les secours, parler à la victime si possible et surveiller sa respiration sans aggraver l’effondrement.'],

        'deshydratation' => ['titre' => 'Donner une solution de réhydratation par petites quantités', 'instruction' => 'Si la personne est consciente et avale normalement, proposer très fréquemment de petites gorgées de solution de réhydratation orale. Arrêter et consulter en urgence si elle ne peut pas boire, vomit tout ou devient confuse.'],
        'fievre' => ['titre' => 'Hydrater et éviter la surchauffe', 'instruction' => 'Installer dans une pièce aérée, retirer les couvertures excessives et faire boire régulièrement si la personne est consciente. Surveiller respiration, conscience, convulsions, raideur de nuque et éruption inhabituelle.'],
        'fievre_nourrisson' => ['titre' => 'Faire évaluer rapidement le nourrisson', 'instruction' => 'Garder le nourrisson avec son accompagnant, éviter de trop le couvrir et poursuivre l’allaitement s’il tète normalement. Ne pas donner de médicament sans dose validée pour son poids et son âge.'],
        'paludisme_signes_graves' => ['titre' => 'Organiser un transfert urgent sans automédication', 'instruction' => 'Installer au repos, faire boire par petites gorgées uniquement si la personne est pleinement consciente et surveiller confusion, convulsion, difficulté respiratoire, vomissements répétés et incapacité à boire.'],
        'diarrhee_aigue' => ['titre' => 'Commencer la réhydratation orale', 'instruction' => 'Donner souvent de petites quantités de solution de réhydratation orale et poursuivre l’alimentation ou l’allaitement toléré. Renforcer le lavage des mains et surveiller les urines et la capacité à boire.'],
        'diarrhee_cholera' => ['titre' => 'Réhydrater immédiatement et organiser le transfert', 'instruction' => 'Commencer sans attendre une solution de réhydratation orale par petites prises répétées si la personne est consciente. Utiliser des précautions d’hygiène strictes et rejoindre rapidement une structure de traitement.'],
        'vomissements_persistants' => ['titre' => 'Réhydrater par très petites gorgées', 'instruction' => 'Faire une courte pause après un vomissement puis proposer de petites gorgées fréquentes de solution de réhydratation. Ne pas forcer et consulter rapidement si aucun liquide n’est gardé ou si la conscience change.'],
        'meningite_signes_alerte' => ['titre' => 'Réduire les stimulations et appeler immédiatement', 'instruction' => 'Installer au calme, limiter la lumière si elle gêne et surveiller conscience, respiration, convulsions et éruption. Ne rien donner par la bouche si la conscience est altérée.'],
        'douleur_abdominale_intense' => ['titre' => 'Installer au repos et ne rien administrer', 'instruction' => 'Laisser la personne choisir la position la moins douloureuse, souvent genoux fléchis, et surveiller malaise, ventre dur, saignement ou vomissements. Ne donner ni nourriture, ni médicament non prescrit.'],
        'cephalee_soudaine' => ['titre' => 'Noter l’heure et rechercher des signes neurologiques', 'instruction' => 'Installer au repos, noter l’heure exacte de début et vérifier parole, visage, force des bras, vision, vomissements et conscience. Appeler immédiatement en cas de début brutal ou signe associé.'],
        'crise_drepanocytaire' => ['titre' => 'Mettre au repos, au chaud et hydrater si possible', 'instruction' => 'Installer confortablement, éviter le froid et faire boire régulièrement si la personne est consciente et sans vomissement. Utiliser seulement son plan antalgique personnel prescrit et consulter rapidement.'],
        'convulsion_febrile_enfant' => ['titre' => 'Protéger l’enfant et chronométrer la crise', 'instruction' => 'Éloigner les objets, protéger la tête, ne pas retenir les mouvements et ne rien mettre dans la bouche. Après la crise, vérifier la respiration, placer sur le côté et faire évaluer l’enfant.'],

        'coup_chaleur' => ['titre' => 'Refroidir immédiatement et activement', 'instruction' => 'Déplacer à l’ombre, retirer les vêtements superflus et refroidir rapidement avec de l’eau, de l’air et des linges humides en attendant les secours. Ne rien faire boire si la conscience est altérée.'],
        'epuisement_chaleur' => ['titre' => 'Mettre au frais et réhydrater progressivement', 'instruction' => 'Installer au repos dans un lieu frais, retirer les vêtements superflus, refroidir avec de l’eau et faire boire une solution de réhydratation par petites gorgées si la personne est pleinement consciente.'],
        'hypothermie' => ['titre' => 'Réchauffer progressivement et manipuler doucement', 'instruction' => 'Mettre à l’abri, retirer les vêtements mouillés, sécher et couvrir avec des couches sèches. Réchauffer d’abord le tronc, manipuler doucement et ne donner une boisson tiède que si la personne est parfaitement consciente.'],
        'foudre' => ['titre' => 'Toucher la victime sans danger après l’impact', 'instruction' => 'La victime ne conserve pas de charge électrique. Vérifier immédiatement respiration et réponse, commencer la réanimation et utiliser un DAE si nécessaire, puis rechercher brûlures et traumatismes.'],

        'saignement_grossesse' => ['titre' => 'Allonger et organiser un transfert obstétrical urgent', 'instruction' => 'Installer la personne sur le côté gauche si cette position est confortable, utiliser une protection propre pour estimer le saignement sans rien introduire dans le vagin et appeler immédiatement.'],
        'eclampsie_suspectee' => ['titre' => 'Protéger pendant la convulsion et appeler immédiatement', 'instruction' => 'Éloigner les objets, protéger la tête, ne rien mettre dans la bouche et noter la durée. Après les secousses, vérifier la respiration et placer sur le côté gauche si possible.'],
        'accouchement_imminent' => ['titre' => 'Préparer un espace propre et accompagner sans tirer', 'instruction' => 'Appeler les secours, préserver l’intimité, installer confortablement et préparer des linges propres et secs. Laisser le bébé venir spontanément, ne pas tirer et le sécher puis le maintenir au chaud contre la mère.'],
        'hemorragie_postpartum' => ['titre' => 'Appeler immédiatement et surveiller le choc', 'instruction' => 'Allonger la mère, la couvrir, placer des protections propres pour absorber le sang et garder le bébé au chaud auprès d’elle si cela est sûr. Ne rien introduire dans le vagin.'],
        'douleur_grossesse_intense' => ['titre' => 'Installer sur le côté et organiser une évaluation urgente', 'instruction' => 'Mettre au repos, de préférence sur le côté gauche si confortable, noter début, localisation, contractions, saignement ou perte de liquide et contacter rapidement une maternité ou les secours.'],

        'nouveau_ne_ne_respire_pas' => ['titre' => 'Sécher, stimuler doucement et appeler immédiatement', 'instruction' => 'Sécher rapidement le nouveau-né, retirer le linge mouillé, le maintenir au chaud et stimuler doucement le dos ou la plante des pieds. S’il ne respire pas normalement, suivre sans délai les instructions de réanimation néonatale données par les secours.'],
        'corps_etranger_enfant' => ['titre' => 'Ne pas retirer à l’aveugle et surveiller la respiration', 'instruction' => 'Ne pas introduire les doigts dans la bouche sans voir l’objet. Si l’enfant tousse et respire, le laisser tousser et faire évaluer l’ingestion ; s’il ne peut plus respirer, appliquer le protocole de désobstruction adapté à son âge.'],
        'intoxication_enfant' => ['titre' => 'Éloigner le produit et appeler avec l’emballage', 'instruction' => 'Retirer le produit hors de portée, conserver son emballage et noter heure et quantité possibles. Ne pas faire vomir, ne rien donner à boire ou manger sans consigne spécialisée et surveiller la respiration.'],
        'deshydratation_enfant' => ['titre' => 'Donner très souvent de petites quantités de réhydratation', 'instruction' => 'Proposer une solution de réhydratation orale à la cuillère ou par petites gorgées répétées et poursuivre l’allaitement. Consulter rapidement si l’enfant est très somnolent, ne boit pas ou urine très peu.'],
        'brulure_enfant' => ['titre' => 'Refroidir immédiatement et prévenir le refroidissement général', 'instruction' => 'Refroidir la brûlure sous l’eau courante tempérée pendant vingt minutes, retirer les vêtements non collés et garder le reste du corps au chaud. Toute brûlure étendue, profonde ou sensible doit être évaluée rapidement.'],
        'traumatisme_cranien_enfant' => ['titre' => 'Garder au repos et surveiller le comportement', 'instruction' => 'Limiter les mouvements, appliquer du froid enveloppé sur une bosse fermée et observer somnolence inhabituelle, vomissements répétés, confusion, convulsion ou difficulté à marcher.'],
        'chute_personne_agee' => ['titre' => 'Ne pas relever avant d’avoir recherché une blessure', 'instruction' => 'Demander où se situe la douleur, vérifier déformation, saignement et capacité à bouger sans forcer. Garder au chaud et appeler si douleur de hanche, tête heurtée, traitement anticoagulant ou impossibilité de se relever.'],
        'plaie_pied_diabetique' => ['titre' => 'Nettoyer, couvrir et supprimer l’appui', 'instruction' => 'Rincer doucement avec de l’eau propre, sécher autour, couvrir avec un pansement propre non serré et éviter tout appui sur la zone. Faire examiner rapidement même si la douleur est faible.'],
    ];

    /**
     * @return array{titre: string, instruction: string}
     */
    public static function get(string $slug): array
    {
        if (!isset(self::ACTIONS[$slug])) {
            throw new \LogicException(sprintf('Aucun geste principal défini pour le protocole maître "%s".', $slug));
        }

        return self::ACTIONS[$slug];
    }
}
